addresses = [    
    ("Ackermann Hans Urs", "Hombergstrasse 12"),
    ("Ackermann Hans Urs", "Hombergstrasse 12"),
    ("Ackermann Hans Urs", "Hombergstrasse 12"),
    ("ACO AG ", "Industrie Kleinzaun, Postfach 197"),
    ("ACO AG ", "Industrie Kleinzaun, Postfach 197"),
    ("ACO AG ", "Industrie Kleinzaun, Postfach 197"),
    ("acoditmo ag, Daniel Iten ", "Tiergartenweg 1"),
    ("acoditmo ag, Daniel Iten ", "Tiergartenweg 1"),
    ("acoditmo ag, Daniel Iten ", "Tiergartenweg 1"),
    ("Aerni Anton", "Allmend 18"),
    ("Aerni Anton", "Allmend 18"),
    ("Aerni Anton", "Allmend 18"),
    ("Aerni Dieter und Stefan", "Mittelgäustr. 16"),
    ("Aerni Dieter und Stefan", "Mittelgäustr. 16"),
    ("Aerni Dieter und Stefan", "Mittelgäustr. 16"),
    ("Aerni Gerhard", "Höllweg 1"),
    ("Aerni Gerhard", "Höllweg 1"),
    ("Aerni Gerhard", "Höllweg 1"),
    ("Aerni Gerhard", "Höllweg 1"),
    ("Aerni Gerhard", "Höllweg 1"),
    ("Aerni Gerhard", "Höllweg 1"),
    ("Aerni-Amberg Nelly", "Mittelgäustr. 26"),
    ("Aerni-Amberg Nelly", "Mittelgäustr. 26"),
    ("Aerni-Amberg Nelly", "Mittelgäustr. 26"),
    ("Aerni-Baisotti Viktor und Sandra", "Schulstrasse 8"),
    ("Aerni-Baisotti Viktor und Sandra", "Schulstrasse 8"),
    ("Aerni-Baisotti Viktor und Sandra", "Schulstrasse 8"),
    ("Aerni-Dubach Peter", "Mittelgäustr. 14"),
    ("Aerni-Dubach Peter", "Mittelgäustr. 14"),
    ("Aerni-Dubach Peter", "Mittelgäustr. 14"),
    ("Aerni-Emmenegger Christoph und Anita", "Mittelgäustr. 54"),
    ("Aerni-Emmenegger Christoph und Anita", "Mittelgäustr. 54"),
    ("Aerni-Emmenegger Christoph und Anita", "Mittelgäustr. 54"),
    ("Aerni-Emmenegger Christoph und Anita", "Mittelgäustr. 54"),
    ("Aerni-Emmenegger Christoph und Anita", "Mittelgäustr. 54"),
    ("Aerni-Lang Daniel + Tanja", "Feldstrasse 2"),
    ("Aerni-Lang Daniel + Tanja", "Feldstrasse 2"),
    ("Aerni-Lang Daniel + Tanja", "Feldstrasse 2"),
    ("Aerni-Meier Walter", "Mittelgäustr. 18"),
    ("Aerni-Meier Walter", "Mittelgäustr. 18"),
    ("Aerni-Meier Walter", "Mittelgäustr. 18"),
    ("Aerni-Nyffenegger Eugen und Erika", "Unterfeldweg 12"),
    ("Aerni-Nyffenegger Eugen und Erika", "Unterfeldweg 12"),
    ("Aerni-Nyffenegger Eugen und Erika", "Unterfeldweg 12"),
    ("Aerni-Obi Martin und Nicole", "Unterfeldweg 20"),
    ("Aerni-Obi Martin und Nicole", "Unterfeldweg 20"),
    ("Aerni-Obi Martin und Nicole", "Unterfeldweg 20"),
    ("Aerni-Schmid Anton und Katharina", "Mittelgäustr. 34"),
    ("Aerni-Schmid Anton und Katharina", "Mittelgäustr. 34"),
    ("Aerni-Schmid Anton und Katharina", "Mittelgäustr. 34"),
    ("Aerni Ramona Hari Pascal und", "Jurastrasse 6"),
    ("Aerni Ramona Hari Pascal und", "Jurastrasse 6"),
    ("Aerni Ramona Hari Pascal und", "Jurastrasse 6"),
    ("Albiker Patrick + Manuela", "Kirchweg 9d"),
    ("Albiker Patrick + Manuela", "Kirchweg 9d"),
    ("Albiker Patrick + Manuela", "Kirchweg 9d"),
    ("Allemann-Marti Frank und Andrea", "Aeschweg 47"),
    ("Allemann-Marti Frank und Andrea", "Aeschweg 47"),
    ("Allemann-Marti Frank und Andrea", "Aeschweg 47"),
    ("Aloisi-Egli Therese", "Banackerstrasse 14"),
    ("Aloisi-Egli Therese", "Banackerstrasse 14"),
    ("Aloisi-Egli Therese", "Banackerstrasse 14"),
    ("Altermatt-Zeltner Roland + Kathrin", "Sonnfeldweg 20"),
    ("Altermatt-Zeltner Roland + Kathrin", "Sonnfeldweg 20"),
    ("Altermatt-Zeltner Roland + Kathrin", "Sonnfeldweg 20"),
    ("Ambühl-Fürst Beat + Franziska", "Niederhofweg 7"),
    ("Ambühl-Fürst Beat + Franziska", "Niederhofweg 7"),
    ("Ambühl-Fürst Beat + Franziska", "Niederhofweg 7"),
    ("Ambühl-Fürst Beat + Franziska", "Niederhofweg 7"),
    ("Amedi Burim", "Banackerstrasse 23a"),
    ("Amedi Burim", "Banackerstrasse 23a"),
    ("Amedi Burim", "Banackerstrasse 23a"),
    ("Ammann Alexandra", "Schütenweg 41"),
    ("Ammann Alexandra", "Schütenweg 41"),
    ("Ammann Alexandra", "Schütenweg 41"),
    ("AmTech GmbH ", "Markstrasse 12"),
    ("AmTech GmbH ", "Markstrasse 12"),
    ("AmTech GmbH ", "Markstrasse 12"),
    ("Anderson  Ian und Gabriela", "Unterfeldweg 18"),
    ("Anderson  Ian und Gabriela", "Unterfeldweg 18"),
    ("Anderson  Ian und Gabriela", "Unterfeldweg 18"),
    ("Angela Wyss Daniel Lauber und", "Schulstrasse 24"),
    ("Angela Wyss Daniel Lauber und", "Schulstrasse 24"),
    ("Angela Wyss Daniel Lauber und", "Schulstrasse 24"),
    ("Annaheim Renate Bossard Roman und", "Aeschweg 15"),
    ("Annaheim Renate Bossard Roman und", "Aeschweg 15"),
    ("Annaheim Renate Bossard Roman und", "Aeschweg 15"),
    ("Antoniadis-Brack Konstantinos", "Markstrasse 7"),
    ("Antoniadis-Brack Konstantinos", "Markstrasse 7"),
    ("Antoniadis-Brack Konstantinos", "Markstrasse 7"),
    ("Aqtashi-Sediqi Mohamad und Habiba", "Bornstrasse 9"),
    ("Aqtashi-Sediqi Mohamad und Habiba", "Bornstrasse 9"),
    ("Aqtashi-Sediqi Mohamad und Habiba", "Bornstrasse 9"),
    ("Arnold Rosmarie", "Lilienweg 6"),
    ("Arnold Rosmarie", "Lilienweg 6"),
    ("Arnold Rosmarie", "Lilienweg 6"),
    ("Auer Christoph", "Mittelgäustr. 21"),
    ("Auer Christoph", "Mittelgäustr. 21"),
    ("Auer Christoph", "Mittelgäustr. 21"),
    ("Auer-Giger Roman + Elisabeth", "Eichenstrasse 5"),
    ("Auer-Giger Roman + Elisabeth", "Eichenstrasse 5"),
    ("Auer-Giger Roman + Elisabeth", "Eichenstrasse 5"),
    ("Autobahnraststätte Gunzgen Nord AG ", ""),
    ("Autobahnraststätte Gunzgen Nord AG ", ""),
    ("Autobahnraststätte Gunzgen Nord AG ", ""),
    ("Autowerkstatt Misteli/Rhode ", "Markstrasse 12"),
    ("Autowerkstatt Misteli/Rhode ", "Markstrasse 12"),
    ("Autowerkstatt Misteli/Rhode ", "Markstrasse 12"),
    ("Avida Immobilien -Treuhand AG ", "Solothurnerstrasse 233"),
    ("Avida Immobilien -Treuhand AG ", "Solothurnerstrasse 233"),
    ("Avida Immobilien -Treuhand AG ", "Solothurnerstrasse 233"),
    ("Ayhan Beste + Gülse", "Banackerstrasse 23"),
    ("Ayhan Beste + Gülse", "Banackerstrasse 23"),
    ("Ayhan Beste + Gülse", "Banackerstrasse 23"),
    ("Bader Tanja Flückiger Pascal und", "Oberfeldweg 28"),
    ("Bader Tanja Flückiger Pascal und", "Oberfeldweg 28"),
    ("Bader Tanja Flückiger Pascal und", "Oberfeldweg 28"),
    ("Bärtschinger Fabio + Künemann Patrizia ", "Schulstrasse 7"),
    ("Bärtschinger Fabio + Künemann Patrizia ", "Schulstrasse 7"),
    ("Bärtschinger Fabio + Künemann Patrizia ", "Schulstrasse 7"),
    ("Baggenstos Franziska Ursula", "Allmend 21"),
    ("Baggenstos Franziska Ursula", "Allmend 21"),
    ("Baggenstos Franziska Ursula", "Allmend 21"),
    ("Bandello Fernando + Mirjam", "Mittelgäustr. 9"),
    ("Bandello Fernando + Mirjam", "Mittelgäustr. 9"),
    ("Bandello Fernando + Mirjam", "Mittelgäustr. 9"),
    ("Bannwart-Gubler André + Karin", "Oberfeldweg 11"),
    ("Bannwart-Gubler André + Karin", "Oberfeldweg 11"),
    ("Bannwart-Gubler André + Karin", "Oberfeldweg 11"),
    ("Bannwart-Kneidinger Brunhilde", "Mittelgäustr. 30"),
    ("Bannwart-Kneidinger Brunhilde", "Mittelgäustr. 30"),
    ("Bannwart-Kneidinger Brunhilde", "Mittelgäustr. 30"),
    ("Bannwart-Kneidinger Brunhilde", "Mittelgäustr. 30"),
    ("Baschung Roman", "Römerweg 3"),
    ("Baschung Roman", "Römerweg 3"),
    ("Baschung Roman", "Römerweg 3"),
    ("Baumann Esther Elisabeth", "Zweigstrasse 8"),
    ("Baumann Esther Elisabeth", "Zweigstrasse 8"),
    ("Baumann Esther Elisabeth", "Zweigstrasse 8"),
    ("Beck-Fürst Marc Robert + Cornelia", "Lischmatt 3"),
    ("Beck-Fürst Marc Robert + Cornelia", "Lischmatt 3"),
    ("Beck-Fürst Marc Robert + Cornelia", "Lischmatt 3"),
    ("Beng-von Arx Lukas + Andrea", "Sonnfeldweg 14"),
    ("Beng-von Arx Lukas + Andrea", "Sonnfeldweg 14"),
    ("Beng-von Arx Lukas + Andrea", "Sonnfeldweg 14"),
    ("Berchtold Sabine", "Dornacherstrasse 29"),
    ("Berchtold Sabine", "Dornacherstrasse 29"),
    ("Berchtold Sabine", "Dornacherstrasse 29"),
    ("Berger Mael", "Bornstrasse 14"),
    ("Berger Mael", "Bornstrasse 14"),
    ("Berger Mael", "Bornstrasse 14"),
    ("Berger-Schneider Werner und Sandra", "Mittelgäustrasse 1"),
    ("Berger-Schneider Werner und Sandra", "Mittelgäustr. 1"),
    ("Berger-Schneider Werner und Sandra", "Mittelgäustr. 1"),
    ("Berger-Schneider Werner und Sandra", "Mittelgäustr. 1"),
    ("Berisha-Leci Nazmi+Zejnepe", "Alte Poststrasse 2"),
    ("Berisha-Leci Nazmi+Zejnepe", "Alte Poststrasse 2"),
    ("Berisha-Leci Nazmi+Zejnepe", "Alte Poststrasse 2"),
    ("Beselica Bajram + Elife", "Allmendstrasse 7"),
    ("Beselica Bajram + Elife", "Allmendstrasse 7"),
    ("Beselica Bajram + Elife", "Allmendstrasse 7"),
    ("Beutler Roland", "Aeschweg 41"),
    ("Beutler Roland", "Aeschweg 41"),
    ("Beutler Roland", "Aeschweg 41"),
    ("Beyeler Konrad", "Allmendstrassse 15"),
    ("Beyeler Konrad", "Allmendstrassse 15"),
    ("Beyeler Konrad", "Allmendstrassse 15"),
    ("Biedermann Oliver", "Schulstrasse 25"),
    ("Biedermann Oliver", "Schulstrasse 25"),
    ("Biedermann Oliver", "Schulstrasse 25"),
    ("Biedermann-Kopp Richard und Brigitte", "Aeschweg 14"),
    ("Biedermann-Kopp Richard und Brigitte", "Aeschweg 14"),
    ("Biedermann-Kopp Richard und Brigitte", "Aeschweg 14"),
    ("Bieri Ursula", "Römerweg 27"),
    ("Bieri Ursula", "Römerweg 27"),
    ("Bieri Ursula", "Römerweg 27"),
    ("Bigler-Büttiker Ernst und Andrea", "Lilienweg 2"),
    ("Bigler-Büttiker Ernst und Andrea", "Lilienweg 2"),
    ("Bigler-Büttiker Ernst und Andrea", "Lilienweg 2"),
    ("Bigler Nadine Eggenschwiler Silvan und", "Sonnfeldweg 6"),
    ("Bigler Nadine Eggenschwiler Silvan und", "Sonnfeldweg 6"),
    ("Bigler Nadine Eggenschwiler Silvan und", "Sonnfeldweg 6"),
    ("Bilecen Ali und Merve", "Unterfeldweg 6"),
    ("Bilecen Ali und Merve", "Unterfeldweg 6"),
    ("Bilecen Ali und Merve", "Unterfeldweg 6"),
    ("Bitterli-Schmid Roger und Gabriela", "Eichenstrasse 8"),
    ("Bitterli-Schmid Roger und Gabriela", "Eichenstrasse 8"),
    ("Bitterli-Schmid Roger und Gabriela", "Eichenstrasse 8"),
    ("Blättler-Baumann Rolf und Eveline", "Kreuzstrasse 6"),
    ("Blättler-Baumann Rolf und Eveline", "Kreuzstrasse 6"),
    ("Blättler-Baumann Rolf und Eveline", "Kreuzstrasse 6"),
    ("Blenke-Fürst Sara", "Sonnfeldweg 5"),
    ("Blenke-Fürst Sara", "Sonnfeldweg 5"),
    ("Blenke-Fürst Sara", "Sonnfeldweg 5"),
    ("Borner Michael + Irene", "Banacker 25"),
    ("Borner Michael + Irene", "Banacker 25"),
    ("Borner Michael + Irene", "Banacker 25"),
    ("Borner-Känzig Peter und Doris", "Markstrasse 5"),
    ("Borner-Känzig Peter und Doris", "Markstrasse 5"),
    ("Borner-Känzig Peter und Doris", "Markstrasse 5"),
    ("Bortis-Zulliger Peter und Doris", "Aeschweg 37"),
    ("Bortis-Zulliger Peter und Doris", "Aeschweg 37"),
    ("Bortis-Zulliger Peter und Doris", "Aeschweg 37"),
    ("Brönnimann Martin und Tamara", "Bornstrasse 18"),
    ("Brönnimann Martin und Tamara", "Bornstrasse 18"),
    ("Brönnimann Martin und Tamara", "Bornstrasse 18"),
    ("Brönnimann-Kernen Beat und Karin", "Niderfeld 16"),
    ("Brönnimann-Kernen Beat und Karin", "Niderfeld 16"),
    ("Brönnimann-Kernen Beat und Karin", "Niderfeld 16"),
    ("Brügger-Marbach Stefan und Ingrid", "Kreuzstrasse 2"),
    ("Brügger-Marbach Stefan und Ingrid", "Kreuzstrasse 2"),
    ("Brügger-Marbach Stefan und Ingrid", "Kreuzstrasse 2"),
    ("Brugger-Studer Hildegard", "Mittelgäustr. 60"),
    ("Brugger-Studer Hildegard", "Mittelgäustr. 60"),
    ("Brugger-Studer Hildegard", "Mittelgäustr. 60"),
    ("Brunner-Giger Annemarie", "Schulstrasse 18"),
    ("Brunner-Giger Annemarie", "Schulstrasse 18"),
    ("Brunner-Giger Annemarie", "Schulstrasse 18"),
    ("Bucher-Reck Markus + Yolanda", "Sonnfeldweg 30"),
    ("Bucher-Reck Markus + Yolanda", "Sonnfeldweg 30"),
    ("Bucher-Reck Markus + Yolanda", "Sonnfeldweg 30"),
    ("Buchs Nazmi + Sonja", "Unterfeldweg 21"),
    ("Buchs Nazmi + Sonja", "Unterfeldweg 21"),
    ("Buchs Nazmi + Sonja", "Unterfeldweg 21"),
    ("Buchs Nazmi + Sonja", "Unterfeldweg 21"),
    ("Buchs Nazmi + Sonja", "Unterfeldweg 21"),
    ("Buchs Nazmi + Sonja", "Unterfeldweg 21"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Mittelgäustrasse 33"),
    ("Bürgergemeinde Gunzgen ", "Markstrasse 16"),
    ("Bürgergemeinde Gunzgen ", "Markstrasse 16"),
    ("Bürgergemeinde Gunzgen ", "Markstrasse 16"),
    ("Bürgergemeinde Gunzgen ", "Markstrasse 16"),
    ("Bürgergemeinde Gunzgen ", "Markstrasse 16"),
    ("Bürgergemeinde Gunzgen ", "Markstrasse 16"),
    ("Büttiker Christian", "Römerweg Ost 21"),
    ("Büttiker Peter", "Römerweg Ost 17"),
    ("Büttiker Peter", "Römerweg Ost 17"),
    ("Büttiker Peter", "Römerweg Ost 17"),
    ("Caderas Jacqueline", "Allmend 11"),
    ("Caderas Jacqueline", "Allmend 11"),
    ("Caderas Jacqueline", "Allmend 11"),
    ("Cengiz Asaf und Eda", "Banackerstrasse 8"),
    ("Cengiz Asaf und Eda", "Banackerstrasse 8"),
    ("Cengiz Asaf und Eda", "Banackerstrasse 8"),
    ("Chhit Chanbo", "Ghölstrasse 16"),
    ("Chhit Chanbo", "Ghölstrasse 16"),
    ("Chhit Chanbo", "Ghölstrasse 16"),
    ("Christen-Rohner Walter und Denise", "Aeschweg 29"),
    ("Christen-Rohner Walter und Denise", "Aeschweg 29"),
    ("Christen-Rohner Walter und Denise", "Aeschweg 29"),
    ("CORATEC AG ", "Industriestrasse 33"),
    ("CORATEC AG ", "Industriestrasse 33"),
    ("CORATEC AG ", "Industriestrasse 33"),
    ("Covarelli Marco", "Banackerstrasse 9"),
    ("Covarelli Marco", "Banackerstrasse 9"),
    ("Covarelli Marco", "Banackerstrasse 9"),
    ("Dätwyler-Steiger Valentin und Eva", "Eichenstrasse 6"),
    ("Dätwyler-Steiger Valentin und Eva", "Eichenstrasse 6"),
    ("Dätwyler-Steiger Valentin und Eva", "Eichenstrasse 6"),
    ("Dallapiazza Sandra", "Lipsmattweg 4"),
    ("Dallapiazza Sandra", "Lipsmattweg 4"),
    ("Dallapiazza Sandra", "Lipsmattweg 4"),
    ("D'Auria Ferdinando+Raffaela", "Oberfeldweg 36"),
    ("D'Auria Ferdinando+Raffaela", "Oberfeldweg 36"),
    ("D'Auria Ferdinando+Raffaela", "Oberfeldweg 36"),
    ("D'Auria Francesca", "Römerweg 18"),
    ("D'Auria Francesca", "Römerweg 18"),
    ("D'Auria Francesca", "Römerweg 18"),
    ("D'Auria Pascal", "Römerweg 16"),
    ("D'Auria Pascal", "Römerweg 16"),
    ("D'Auria Pascal", "Römerweg 16"),
    ("Degelmann-Willi Jules", "Unterfeldweg 11"),
    ("Degelmann-Willi Jules", "Unterfeldweg 11"),
    ("Degelmann-Willi Jules", "Unterfeldweg 11"),
    ("De Haan John", "Storchengasse 3"),
    ("De Haan John", "Storchengasse 3"),
    ("De Haan John", "Storchengasse 3"),
    ("Demirsal Ali + Yeter", "Bornstrasse 4A"),
    ("Demirsal Ali + Yeter", "Bornstrasse 4A"),
    ("Demirsal Ali + Yeter", "Bornstrasse 4A"),
    ("Dietschi René", "Lipsmattweg 1"),
    ("Dietschi René", "Lipsmattweg 1"),
    ("Dietschi René", "Lipsmattweg 1"),
    ("Dobay Andreas", "Unterfeldweg 27"),
    ("Dobay Andreas", "Unterfeldweg 27"),
    ("Dobay Andreas", "Unterfeldweg 27"),
    ("Dörfliger Thomas", "Kreuzstrassse 8"),
    ("Dörfliger Thomas", "Kreuzstrassse 8"),
    ("Dörfliger Thomas", "Kreuzstrassse 8"),
    ("Dreier-Hägler Ralf + Nicole", "Kreuzstrasse 9"),
    ("Dreier-Hägler Ralf + Nicole", "Kreuzstrasse 9"),
    ("Dreier-Hägler Ralf + Nicole", "Kreuzstrasse 9"),
    ("dreierfashion4you AG ", "Klärstrasse 10"),
    ("dreierfashion4you AG ", "Klärstrasse 10"),
    ("dreierfashion4you AG ", "Klärstrasse 10"),
    ("dreierfashion4you AG ", "Klärstrasse 10"),
    ("Düblin  Sascha", "Allmend 25"),
    ("Düblin  Sascha", "Allmend 25"),
    ("Düblin  Sascha", "Allmend 25"),
    ("Egger Christian", "Unterfeldweg 25"),
    ("Egger Christian", "Unterfeldweg 25"),
    ("Egger Christian", "Unterfeldweg 25"),
    ("Eggnauer-Aebi Heinz + Gabriela", "Kreuzstrasse 10"),
    ("Eggnauer-Aebi Heinz + Gabriela", "Kreuzstrasse 10"),
    ("Eggnauer-Aebi Heinz + Gabriela", "Kreuzstrasse 10"),
    ("Ehrensperger Tiina", "Bergstrasse 30"),
    ("Ehrensperger Tiina", "Bergstrasse 30"),
    ("Ehrensperger Tiina", "Bergstrasse 30"),
    ("Eigenmann-Fluri Jacqueline", "Oberfeldweg 26"),
    ("Eigenmann-Fluri Jacqueline", "Oberfeldweg 26"),
    ("Eigenmann-Fluri Jacqueline", "Oberfeldweg 26"),
    ("Eigentümergemeinschaft Aeby & Halfmann ", "Banackerstrasse 17"),
    ("Eigentümergemeinschaft Aeby & Halfmann ", "Banackerstrasse 17"),
    ("Eigentümergemeinschaft Aeby & Halfmann ", "Banackerstrasse 17"),
    ("Einwohnergemeinde Gunzgen ", "Allmendstrasse 2"),
    ("Einwohnergemeinde Gunzgen ", "Allmendstrasse 2"),
    ("Einwohnergemeinde Gunzgen ", "Allmendstrasse 2"),
    ("Einwohnergemeinde Gunzgen ", "Allmendstrasse 2"),
    ("Einwohnergemeinde Gunzgen ", "Allmendstrasse 2"),
    ("Einwohnergemeinde Gunzgen ", "Allmendstrasse 2"),
    ("Einwohnergemeinde Gunzgen ", "Allmendstrasse 2"),
    ("Einwohnergemeinde Kappel ", ""),
    ("Einwohnergemeinde Kappel ", ""),
    ("Einwohnergemeinde Kappel ", ""),
    ("Epp-Mazzoleni Martina", "Hauptstrasse 10"),
    ("Epp-Mazzoleni Martina", "Hauptstrasse 10"),
    ("Epp-Mazzoleni Martina", "Hauptstrasse 10"),
    ("Erbengemeinschaft Heim Martin ", "Erlinsbacherstrasse 17"),
    ("Erbengemeinschaft Heim Martin ", "Erlinsbacherstrasse 17"),
    ("Erbengemeinschaft Heim Martin ", "Erlinsbacherstrasse 17"),
    ("Erne AG Bauunternehmung ", "Postfach 229"),
    ("Erne AG Bauunternehmung ", "Postfach 229"),
    ("Erne AG Bauunternehmung ", "Postfach 229"),
    ("Erne AG Bauunternehmung ", "Postfach 229"),
    ("Erne AG Bauunternehmung ", "Postfach 229"),
    ("Erne AG Bauunternehmung ", "Postfach 229"),
    ("Erne Seiichi Alvise Leonardo", "Bornstrasse 5"),
    ("Erne Seiichi Alvise Leonardo", "Bornstrasse 5"),
    ("Erne Seiichi Alvise Leonardo", "Bornstrasse 5"),
    ("Fankhauser-Vogel Beat + Nadja", "Unterfeldweg 7"),
    ("Fankhauser-Vogel Beat + Nadja", "Unterfeldweg 7"),
    ("Fankhauser-Vogel Beat + Nadja", "Unterfeldweg 7"),
    ("Ferreira-Sampaio José", "Mittelgäustr. 31"),
    ("Ferreira-Sampaio José", "Mittelgäustr. 31"),
    ("Ferreira-Sampaio José", "Mittelgäustr. 31"),
    ("Fischer Alessandro und Melinda", "Kirchweg 9"),
    ("Fischer Alessandro und Melinda", "Kirchweg 9"),
    ("Fischer Alessandro und Melinda", "Kirchweg 9"),
    ("Fischer Raffael und Chantal", "Kreuzstrasse 4"),
    ("Fischer Raffael und Chantal", "Kreuzstrasse 4"),
    ("Fischer Raffael und Chantal", "Kreuzstrasse 4"),
    ("Fischer-Sager Martha", "Schulstrasse 12"),
    ("Fischer-Sager Martha", "Schulstrasse 12"),
    ("Fischer-Sager Martha", "Schulstrasse 12"),
    ("Flückiger Rolf+Stefanie", "Bornstrasse 2"),
    ("Flückiger Rolf+Stefanie", "Bornstrasse 2"),
    ("Flückiger Rolf+Stefanie", "Bornstrasse 2"),
    ("Flückiger-Stöckli Dieter und Roswitha", "Jurastrasse 8"),
    ("Flückiger-Stöckli Dieter und Roswitha", "Jurastrasse 8"),
    ("Flückiger-Stöckli Dieter und Roswitha", "Jurastrasse 8"),
    ("Flury Markus", "Schulstrasse 28"),
    ("Flury Markus", "Schulstrasse 28"),
    ("Flury Markus", "Schulstrasse 28"),
    ("Freuler-Müller Ernst und Sonja", "Unterfeldweg 29"),
    ("Freuler-Müller Ernst und Sonja", "Unterfeldweg 29"),
    ("Freuler-Müller Ernst und Sonja", "Unterfeldweg 29"),
    ("Frey-Hinni Reto + Sabrina", "Banackerstrasse 12"),
    ("Frey-Hinni Reto + Sabrina", "Banackerstrasse 12"),
    ("Frey-Hinni Reto + Sabrina", "Banackerstrasse 12"),
    ("Fritschi-Hüssy Erwin", "Allmendstrasse 27"),
    ("Fritschi-Hüssy Erwin", "Allmendstrasse 27"),
    ("Fritschi-Hüssy Erwin", "Allmendstrasse 27"),
    ("Fürst Angelina", "Aeschweg 5"),
    ("Fürst Angelina", "Aeschweg 5"),
    ("Fürst Angelina", "Aeschweg 5"),
    ("Fürst Roland", "Allmendstrasse 18"),
    ("Fürst Roland", "Allmendstrasse 18"),
    ("Fürst Roland", "Allmendstrasse 18"),
    ("Fürst Tobias Benjamin", "Mittgelgäustrasse 32"),
    ("Fürst Tobias Benjamin", "Mittgelgäustrasse 32"),
    ("Fürst Tobias Benjamin", "Mittgelgäustrasse 32"),
    ("Fürst Tobias Benjamin", "Mittgelgäustrasse 32"),
    ("Fürst-Friedauer Roland und Gabriela", "Feldstrasse 4"),
    ("Fürst-Friedauer Roland und Gabriela", "Feldstrasse 4"),
    ("Fürst-Friedauer Roland und Gabriela", "Feldstrasse 4"),
    ("Fürst-Fürst Peter und Agnes", "Kirchweg 6"),
    ("Fürst-Fürst Peter und Agnes", "Kirchweg 6"),
    ("Fürst-Fürst Peter und Agnes", "Kirchweg 6"),
    ("Fürst-Huber Valentin und Rita", "Aeschweg 3"),
    ("Fürst-Huber Valentin und Rita", "Aeschweg 3"),
    ("Fürst-Huber Valentin und Rita", "Aeschweg 3"),
    ("Fürst-Huser Philipp+Yvonne", "Römerweg Ost 5"),
    ("Fürst-Huser Philipp+Yvonne", "Römerweg Ost 5"),
    ("Fürst-Huser Philipp+Yvonne", "Römerweg Ost 5"),
    ("Fürst-Kamber Josef", "Allmendstrasse 20"),
    ("Fürst-Kamber Josef", "Allmendstrasse 20"),
    ("Fürst-Kamber Josef", "Allmendstrasse 20"),
    ("Fürst-Meyer Andreas und Susi", "Alte Poststrasse 8"),
    ("Fürst-Meyer Andreas und Susi", "Alte Poststrasse 8"),
    ("Fürst-Meyer Andreas und Susi", "Alte Poststrasse 8"),
    ("Fürst-Pirovino André + Barbara", "Schulstrasse 36"),
    ("Fürst-Pirovino André + Barbara", "Schulstrasse 36"),
    ("Fürst-Pirovino André + Barbara", "Schulstrasse 36"),
    ("Fürst-Raid Hermine", "Unterfeldweg 2"),
    ("Fürst-Raid Hermine", "Unterfeldweg 2"),
    ("Fürst-Raid Hermine", "Unterfeldweg 2"),
    ("Fürst-Staub Adrian + Christine", "Allmendstrasse 25"),
    ("Fürst-Staub Adrian + Christine", "Allmendstrasse 25"),
    ("Fürst-Staub Adrian + Christine", "Allmendstrasse 25"),
    ("Fürst-Walther Johanna", "Spitzrüti 2"),
    ("Fürst-Walther Johanna", "Spitzrüti 2"),
    ("Fürst-Walther Johanna", "Spitzrüti 2"),
    ("Gaiser-Gackenheimer Mario + Ursel", "Alpenweg 4"),
    ("Gaiser-Gackenheimer Mario + Ursel", "Alpenweg 4"),
    ("Gaiser-Gackenheimer Mario + Ursel", "Alpenweg 4"),
    ("Gasser Beat", "Markstrasse 8"),
    ("Gasser Beat", "Markstrasse 8"),
    ("Gasser Beat", "Markstrasse 8"),
    ("Gasser-Eichenberger Andreas+Brigitte", "Niderfeld 12"),
    ("Gasser-Eichenberger Andreas+Brigitte", "Niderfeld 12"),
    ("Gasser-Eichenberger Andreas+Brigitte", "Niderfeld 12"),
    ("Gasser-Kohler Daniel + Monika", "Bornstrasse 6"),
    ("Gasser-Kohler Daniel + Monika", "Bornstrasse 6"),
    ("Gasser-Kohler Daniel + Monika", "Bornstrasse 6"),
    ("GEBA Genossenschaft für kollektive Berufs- und Altersvorsorge Zofingen ", "Pfistergasse 38"),
    ("GEBA Genossenschaft für kollektive Berufs- und Altersvorsorge Zofingen ", "Pfistergasse 38"),
    ("GEBA Genossenschaft für kollektive Berufs- und Altersvorsorge Zofingen ", "Pfistergasse 38"),
    ("Gerber-Dubler Marcel + Carmen", "Bornstrasse 3"),
    ("Gerber-Dubler Marcel + Carmen", "Bornstrasse 3"),
    ("Gerber-Dubler Marcel + Carmen", "Bornstrasse 3"),
    ("Gerber-Krähenbühl René und Jolanda", "Oberfeldweg 38"),
    ("Gerber-Krähenbühl René und Jolanda", "Oberfeldweg 38"),
    ("Gerber-Krähenbühl René und Jolanda", "Oberfeldweg 38"),
    ("Gerhard-Walker Heinz", "Ghölstrase 18"),
    ("Gerhard-Walker Heinz", "Ghölstrase 18"),
    ("Gerhard-Walker Heinz", "Ghölstrase 18"),
    ("Giaccari Raphael+Patrizia", "Römerweg 5"),
    ("Giaccari Raphael+Patrizia", "Römerweg 5"),
    ("Giaccari Raphael+Patrizia", "Römerweg 5"),
    ("Gizzi-von Arb Rainer + Gisela", "Markstrasse 3"),
    ("Gizzi-von Arb Rainer + Gisela", "Markstrasse 3"),
    ("Gizzi-von Arb Rainer + Gisela", "Markstrasse 3"),
    ("GL Immobilien St. Moritz AG ", "Untere Grabenstrasse 14a"),
    ("GL Immobilien St. Moritz AG ", "Untere Grabenstrasse 14a"),
    ("GL Immobilien St. Moritz AG ", "Untere Grabenstrasse 14a"),
    ("GL Immobilien St. Moritz AG ", "Untere Grabenstrasse 14a"),
    ("GL Immobilien St. Moritz AG ", "Untere Grabenstrasse 14a"),
    ("GL Immobilien St. Moritz AG ", "Untere Grabenstrasse 14a"),
    ("Göggel Willi", "Sonnfeldweg 28"),
    ("Göggel Willi", "Sonnfeldweg 28"),
    ("Göggel Willi", "Sonnfeldweg 28"),
    ("Graf-Ruch Roman + Petra", "Römerweg 7"),
    ("Graf-Ruch Roman + Petra", "Römerweg 7"),
    ("Graf-Ruch Roman + Petra", "Römerweg 7"),
    ("Grieder-Kielholz Simon + Gaby", "Unterfeldweg 31"),
    ("Grieder-Kielholz Simon + Gaby", "Unterfeldweg 31"),
    ("Grieder-Kielholz Simon + Gaby", "Unterfeldweg 31"),
    ("Grimbichler Heinrich", "Aeschweg 35"),
    ("Grimbichler Heinrich", "Aeschweg 35"),
    ("Grimbichler Heinrich", "Aeschweg 35"),
    ("Grossenbacher-Bleuer Daniel und Margot", "Aeschweg 27"),
    ("Grossenbacher-Bleuer Daniel und Margot", "Aeschweg 27"),
    ("Grossenbacher-Bleuer Daniel und Margot", "Aeschweg 27"),
    ("Grütter-Flühmann Liliane", "Allmend 10"),
    ("Grütter-Flühmann Liliane", "Allmend 10"),
    ("Grütter-Flühmann Liliane", "Allmend 10"),
    ("Gutschier-Preusser Reto + Rebecca", "Aeschweg 17"),
    ("Gutschier-Preusser Reto + Rebecca", "Aeschweg 17"),
    ("Gutschier-Preusser Reto + Rebecca", "Aeschweg 17"),
    ("Hair Style ", "Mittelgäustrasse 35"),
    ("Hair Style ", "Mittelgäustrasse 35"),
    ("Hair Style ", "Mittelgäustrasse 35"),
    ("Haller Beatrice + Elisabeth", "Römerweg Ost 12"),
    ("Haller Beatrice + Elisabeth", "Römerweg Ost 12"),
    ("Haller Beatrice + Elisabeth", "Römerweg Ost 12"),
    ("Haller Rolf", "Industriestrasse 5"),
    ("Haller Rolf", "Industriestrasse 5"),
    ("Haller Rolf", "Industriestrasse 5"),
    ("Haller-Zünd Marius+Julia", "Unterfeldweg 33"),
    ("Haller-Zünd Marius+Julia", "Unterfeldweg 33"),
    ("Haller-Zünd Marius+Julia", "Unterfeldweg 33"),
    ("Hari-Hofer Peter + Ruth", "Eichenstrasse 12"),
    ("Hari-Hofer Peter + Ruth", "Eichenstrasse 12"),
    ("Hari-Hofer Peter + Ruth", "Eichenstrasse 12"),
    ("Hartung-Redzepovski Lydia Redjepi Nuredin und ", "Mittelgäustr. 19"),
    ("Hartung-Redzepovski Lydia Redjepi Nuredin und ", "Mittelgäustr. 19"),
    ("Hartung-Redzepovski Lydia Redjepi Nuredin und ", "Mittelgäustr. 19"),
    ("Hasenfratz-Zumbühl Roland und Susanne", "Banackerstrasse 5"),
    ("Hasenfratz-Zumbühl Roland und Susanne", "Banackerstrasse 5"),
    ("Hasenfratz-Zumbühl Roland und Susanne", "Banackerstrasse 5"),
    ("Hauser-von Arb Annette", "Markstrasse 17"),
    ("Hauser-von Arb Annette", "Markstrasse 17"),
    ("Hauser-von Arb Annette", "Markstrasse 17"),
    ("Heeb Edda", "Allmend 4"),
    ("Heeb Edda", "Allmend 4"),
    ("Heeb Edda", "Allmend 4"),
    ("Heeb-Hirsiger Claudia", "Unterfeldweg 16"),
    ("Heeb-Hirsiger Claudia", "Unterfeldweg 16"),
    ("Heeb-Hirsiger Claudia", "Unterfeldweg 16"),
    ("Heiniger-Aerni Dieter + Ursula", "Allmendstrasse 12"),
    ("Heiniger-Aerni Dieter + Ursula", "Allmendstrasse 12"),
    ("Heiniger-Aerni Dieter + Ursula", "Allmendstrasse 12"),
    ("Heutschi Kurt", "Kreuzstrasse 14"),
    ("Heutschi Kurt", "Kreuzstrasse 14"),
    ("Heutschi Kurt", "Kreuzstrasse 14"),
    ("Hilfiker Marcel", "Banackerstrasse 6"),
    ("Hilfiker Marcel", "Banackerstrasse 6"),
    ("Hilfiker Marcel", "Banackerstrasse 6"),
    ("Hiltbrunner-Marbet Max + Rita ", "Allmendstrasse 31 + 33"),
    ("Hiltbrunner-Marbet Max + Rita ", "Allmendstrasse 31 + 33"),
    ("Hiltbrunner-Marbet Max + Rita ", "Allmendstrasse 31 + 33"),
    ("Hintermann Sandra ", "Römerweg 11"),
    ("Hintermann Sandra ", "Römerweg 11"),
    ("Hintermann Sandra ", "Römerweg 11"),
    ("Hirschi Walter", "Sonnfeldweg 9"),
    ("Hirschi Walter", "Sonnfeldweg 9"),
    ("Hirschi Walter", "Sonnfeldweg 9"),
    ("Hodel Stefan", "Fabrikstrasse 6E"),
    ("Hodel Stefan", "Fabrikstrasse 6E"),
    ("Hodel Stefan", "Fabrikstrasse 6E"),
    ("Hodel Stefan", "Fabrikstrasse 6E"),
    ("Hodel Stefan", "Fabrikstrasse 6E"),
    ("Hof-Borer Urs und Kathrin", "Unterfeldweg 8"),
    ("Hof-Borer Urs und Kathrin", "Unterfeldweg 8"),
    ("Hof-Borer Urs und Kathrin", "Unterfeldweg 8"),
    ("Hofer-Fürst Walter und Barbara", "Aeschweg 25"),
    ("Hofer-Fürst Walter und Barbara", "Aeschweg 25"),
    ("Hofer-Fürst Walter und Barbara", "Aeschweg 25"),
    ("Hofer-Küng Felix + Judith", "Jurastrasse 5"),
    ("Hofer-Küng Felix + Judith", "Jurastrasse 5"),
    ("Hofer-Küng Felix + Judith", "Jurastrasse 5"),
    ("Hofmann Anhänger AG ", "Allmendstrasse 1"),
    ("Hofmann Anhänger AG ", "Allmendstrasse 1"),
    ("Hollenstein Max", "Sonnfeldweg 4"),
    ("Hollenstein Max", "Sonnfeldweg 4"),
    ("Hollenstein Max", "Sonnfeldweg 4"),
    ("Horisberger Verena", "Römerweg Ost 15"),
    ("Horisberger Verena", "Römerweg Ost 15"),
    ("Horisberger Verena", "Römerweg Ost 15"),
    ("Horisberger Verena", "Römerweg Ost 15"),
    ("Horisberger-Blaser Verena", "Römerweg Ost 15"),
    ("Horisberger-Blaser Verena", "Römerweg Ost 15"),
    ("Horisberger-Blaser Verena", "Römerweg Ost 15"),
    ("Horisberger-Blaser Verena", "Römerweg Ost 15"),
    ("Horisberger-Blaser Verena", "Römerweg Ost 15"),
    ("Horisberger-Blaser Verena", "Römerweg Ost 15"),
    ("Hosennen Inge Amherd Markus und", "Aeschweg 19"),
    ("Hosennen Inge Amherd Markus und", "Aeschweg 19"),
    ("Hosennen Inge Amherd Markus und", "Aeschweg 19"),
    ("Huber Rolf", "Kirchweg 2"),
    ("Huber Rolf", "Kirchweg 2"),
    ("Huber Rolf", "Kirchweg 2"),
    ("Hügi-Müller Alfred", "Schulstrasse 22"),
    ("Hügi-Müller Alfred", "Schulstrasse 22"),
    ("Hügi-Müller Alfred", "Schulstrasse 22"),
    ("Hürzeler-Tröhler René + Sandra", "Sonnfeldweg 11"),
    ("Hürzeler-Tröhler René + Sandra", "Sonnfeldweg 11"),
    ("Hürzeler-Tröhler René + Sandra", "Sonnfeldweg 11"),
    ("Hug-Desax Urs und Olivia", "Hügelweg 7"),
    ("Hug-Desax Urs und Olivia", "Hügelweg 7"),
    ("Hug-Desax Urs und Olivia", "Hügelweg 7"),
    ("Hug-Gisler Hans + Erna", "Oberfeldweg 18"),
    ("Hug-Gisler Hans + Erna", "Oberfeldweg 18"),
    ("Hug-Gisler Hans + Erna", "Oberfeldweg 18"),
    ("Hug-Grütter Josef", "Schulstrasse 20"),
    ("Hug-Grütter Josef", "Schulstrasse 20"),
    ("Hug-Grütter Josef", "Schulstrasse 20"),
    ("Hug-Lüscher Arthur", "Hanselmattweg 1"),
    ("Hug-Lüscher Arthur", "Hanselmattweg 1"),
    ("Hug-Lüscher Arthur", "Hanselmattweg 1"),
    ("Hug-Lüthi Edith", "Alte Poststrasse 9"),
    ("Hug-Lüthi Edith", "Alte Poststrasse 9"),
    ("Hug-Lüthi Edith", "Alte Poststrasse 9"),
    ("Hummel-Zaugg Erika", "Banackerstrasse 2"),
    ("Hummel-Zaugg Erika", "Banackerstrasse 2"),
    ("Hummel-Zaugg Erika", "Banackerstrasse 2"),
    ("Hunziker Hannes David", "Leuenallee 18"),
    ("Hunziker Hannes David", "Leuenallee 18"),
    ("Hunziker Hannes David", "Leuenallee 18"),
    ("Hunziker-Bitterli Jörg und Jacqueline", "Kreuzstrasse 12"),
    ("Hunziker-Bitterli Jörg und Jacqueline", "Kreuzstrasse 12"),
    ("Hunziker-Bitterli Jörg und Jacqueline", "Kreuzstrasse 12"),
    ("Hurschler Peter", "Unterfeldweg 4"),
    ("Hurschler Peter", "Unterfeldweg 4"),
    ("Hurschler Peter", "Unterfeldweg 4"),
    ("Huser Peter + Maria", "Mittelgäustrasse 62"),
    ("Huser Peter + Maria", "Mittelgäustrasse 62"),
    ("Huser Peter + Maria", "Mittelgäustrasse 62"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immobiliengesellsch. Manuela AG ", "Dornacherstrasse 24"),
    ("Immopart AG ", "Bettlachstrasse 39"),
    ("Immopart AG ", "Bettlachstrasse 39"),
    ("Immopart AG ", "Bettlachstrasse 39"),
    ("Inauen Bruno", "Allmendstrasse 19"),
    ("Inauen Bruno", "Allmendstrasse 19"),
    ("Inauen Bruno", "Allmendstrasse 19"),
    ("Inauen-Janda Markus", "Banackerstrasse 16"),
    ("Inauen-Janda Markus", "Banackerstrasse 16"),
    ("Inauen-Janda Markus", "Banackerstrasse 16"),
    ("InduBau AG ", "Höllweg 7"),
    ("InduBau AG ", "Höllweg 7"),
    ("InduBau AG ", "Höllweg 7"),
    ("InduBau AG ", "Höllweg 7"),
    ("InduBau AG ", "Höllweg 7"),
    ("InduBau AG ", "Höllweg 7"),
    ("Iseli-Mumenthaler Daniel und Jeannette", "Eichenstrasse 4"),
    ("Iseli-Mumenthaler Daniel und Jeannette", "Eichenstrasse 4"),
    ("Iseli-Mumenthaler Daniel und Jeannette", "Eichenstrasse 4"),
    ("Iseli-Recher Roger und Susi", "Aeschweg 43"),
    ("Iseli-Recher Roger und Susi", "Aeschweg 43"),
    ("Iseli-Recher Roger und Susi", "Aeschweg 43"),
    ("ITZ Immobilien Treuhand AG Zofingen ", "Nationalbahnweg 6"),
    ("ITZ Immobilien Treuhand AG Zofingen ", "Nationalbahnweg 6"),
    ("ITZ Immobilien Treuhand AG Zofingen ", "Nationalbahnweg 6"),
    ("Jäggi-von Arx Stephan+Monika", "Kaltbachstrasse 1"),
    ("Jäggi-von Arx Stephan+Monika", "Kaltbachstrasse 1"),
    ("Jäggi-von Arx Stephan+Monika", "Kaltbachstrasse 1"),
    ("Jenni Andreas + Sandra", "Kirchweg 9c"),
    ("Jenni Andreas + Sandra", "Kirchweg 9c"),
    ("Jenni Andreas + Sandra", "Kirchweg 9c"),
    ("Jordi Emil", "Aeschweg 10"),
    ("Jordi Emil", "Aeschweg 10"),
    ("Jordi Emil", "Aeschweg 10"),
    ("Jost-Giger Johann-Ulrich und Hanni", "Industriestrasse 10"),
    ("Jost-Giger Johann-Ulrich und Hanni", "Industriestrasse 10"),
    ("Jost-Giger Johann-Ulrich und Hanni", "Industriestrasse 10"),
    ("Kämpf Otto", "Banackerstrasse 10"),
    ("Kämpf Otto", "Banackerstrasse 10"),
    ("Kämpf Otto", "Banackerstrasse 10"),
    ("Kaever Thor + Aden Martina ", "Oberfeldweg 32"),
    ("Kaever Thor + Aden Martina ", "Oberfeldweg 32"),
    ("Kaever Thor + Aden Martina ", "Oberfeldweg 32"),
    ("Kallmann Kurt + Käthi", "Nationalbahnweg "),
    ("Kallmann Kurt + Käthi", "Nationalbahnweg "),
    ("Kallmann Kurt + Käthi", "Nationalbahnweg "),
    ("Kamber Charles", "Oberfeldweg 8"),
    ("Kamber Charles", "Oberfeldweg 8"),
    ("Kamber Charles", "Oberfeldweg 8"),
    ("Kamber-Gehret Urs und Katharina", "Oberfeldweg 2"),
    ("Kamber-Gehret Urs und Katharina", "Oberfeldweg 2"),
    ("Kamber-Gehret Urs und Katharina", "Oberfeldweg 2"),
    ("Kamber-Kissling Paul + Edith", "Mittelgäustr. 10"),
    ("Kamber-Kissling Paul + Edith", "Mittelgäustr. 10"),
    ("Kamber-Kissling Paul + Edith", "Mittelgäustr. 10"),
    ("Kameric-Celikovic Fuad+Fatima", "Lilienweg 8"),
    ("Kameric-Celikovic Fuad+Fatima", "Lilienweg 8"),
    ("Kameric-Celikovic Fuad+Fatima", "Lilienweg 8"),
    ("Kamm-Levova Thomas + Zdenka", "Mittelgäustr. 12"),
    ("Kamm-Levova Thomas + Zdenka", "Mittelgäustr. 12"),
    ("Kamm-Levova Thomas + Zdenka", "Mittelgäustr. 12"),
    ("Kandiah Vigneshwaran", "Alte Poststrasse 7"),
    ("Kandiah Vigneshwaran", "Alte Poststrasse 7"),
    ("Kandiah Vigneshwaran", "Alte Poststrasse 7"),
    ("KaRo GmbH ", "Gheidgraben 10"),
    ("KaRo GmbH ", "Gheidgraben 10"),
    ("KaRo GmbH ", "Gheidgraben 10"),
    ("Kaufmann Urs", "Mittelgäustrasse 20"),
    ("Kaufmann Urs", "Mittelgäustrasse 20"),
    ("Kaufmann Urs", "Mittelgäustrasse 20"),
    ("Kaufmann-Luder Ralf+Michaela", "Industriestrasse 3"),
    ("Kaufmann-Luder Ralf+Michaela", "Industriestrasse 3"),
    ("Kaufmann-Luder Ralf+Michaela", "Industriestrasse 3"),
    ("Kauz Egger Lisbeth Egger Jean-Paul und", "Römerweg 29"),
    ("Kauz Egger Lisbeth Egger Jean-Paul und", "Römerweg 29"),
    ("Kauz Egger Lisbeth Egger Jean-Paul und", "Römerweg 29"),
    ("Keepcool Transport AG ", "Klärstrasse 3"),
    ("Keepcool Transport AG ", "Klärstrasse 3"),
    ("Keepcool Transport AG ", "Klärstrasse 3"),
    ("Keepcool Transport AG ", "Klärstrasse 3"),
    ("Keepcool Transport AG ", "Klärstrasse 3"),
    ("Keller-Fürst André + Regula", "Lischmatt 9"),
    ("Keller-Fürst André + Regula", "Lischmatt 9"),
    ("Keller-Fürst André + Regula", "Lischmatt 9"),
    ("Keller-Huser Hanspeter und Fabienne", "Bornstrasse 10"),
    ("Keller-Huser Hanspeter und Fabienne", "Bornstrasse 10"),
    ("Keller-Huser Hanspeter und Fabienne", "Bornstrasse 10"),
    ("Keusch-Hug Robert", "Allmendstrasse 11"),
    ("Keusch-Hug Robert", "Allmendstrasse 11"),
    ("Keusch-Hug Robert", "Allmendstrasse 11"),
    ("Kieswerk Gunzgen AG ", "Härkingerstrasse 1"),
    ("Kieswerk Gunzgen AG ", "Härkingerstrasse 1"),
    ("Kieswerk Gunzgen AG ", "Härkingerstrasse 1"),
    ("Kieswerk Gunzgen AG ", "Härkingerstrasse 1"),
    ("Kieswerk Gunzgen AG ", "Härkingerstrasse 1"),
    ("Kieswerk Gunzgen AG ", "Härkingerstrasse 1"),
    ("Kieswerk Gunzgen AG ", "Härkingerstrasse 1"),
    ("Kieswerk Gunzgen AG ", "Härkingerstrasse 1"),
    ("Kissling-Kupferschmied Rudolf", "Aeschweg 24"),
    ("Kissling-Kupferschmied Rudolf", "Aeschweg 24"),
    ("Kissling-Kupferschmied Rudolf", "Aeschweg 24"),
    ("Klauser Nadia", "Im Bättel 202"),
    ("Klauser Nadia", "Im Bättel 202"),
    ("Klauser Nadia", "Im Bättel 202"),
    ("Knubel Thomas", "Fulenbacherstrasse 50"),
    ("Knubel Thomas", "Fulenbacherstrasse 50"),
    ("Knubel Thomas", "Fulenbacherstrasse 50"),
    ("Koster Christoph", "Allmendstrasse 24"),
    ("Koster Christoph", "Allmendstrasse 24"),
    ("Koster Christoph", "Allmendstrasse 24"),
    ("Krähenbühl Sascha", "Allmend 17"),
    ("Krähenbühl Sascha", "Allmend 17"),
    ("Krähenbühl Sascha", "Allmend 17"),
    ("Krähenbühl-Aebi Bethli", "Oberfeldweg 21"),
    ("Krähenbühl-Aebi Bethli", "Oberfeldweg 21"),
    ("Krähenbühl-Aebi Bethli", "Oberfeldweg 21"),
    ("Krähenbühl-Lanz Martin + Karin", "Oberfeldweg 15"),
    ("Krähenbühl-Lanz Martin + Karin", "Oberfeldweg 15"),
    ("Krähenbühl-Lanz Martin + Karin", "Oberfeldweg 15"),
    ("Krähenbühl-Marquart Daniel und Jacqueline", "Kaltbachstrasse 5"),
    ("Krähenbühl-Marquart Daniel und Jacqueline", "Kaltbachstrasse 5"),
    ("Krähenbühl-Marquart Daniel und Jacqueline", "Kaltbachstrasse 5"),
    ("Krähenbühl-Studer Hansruedi und Ruth", "Kaltbachstrasse 7"),
    ("Krähenbühl-Studer Hansruedi und Ruth", "Kaltbachstrasse 7"),
    ("Krähenbühl-Studer Hansruedi und Ruth", "Kaltbachstrasse 7"),
    ("Kürschner Matthias und Nicole", "Allmendstrasse 28"),
    ("Kürschner Matthias und Nicole", "Allmendstrasse 28"),
    ("Kürschner Matthias und Nicole", "Allmendstrasse 28"),
    ("Kyburz-Rattaggi André + Tanja", "Banackerstrasse 28"),
    ("Kyburz-Rattaggi André + Tanja", "Banackerstrasse 28"),
    ("Kyburz-Rattaggi André + Tanja", "Banackerstrasse 28"),
    ("Lachmuth-Fürst Theodor + Helena Ursula", "Oberfeldweg 10"),
    ("Lachmuth-Fürst Theodor + Helena Ursula", "Oberfeldweg 10"),
    ("Lachmuth-Fürst Theodor + Helena Ursula", "Oberfeldweg 10"),
    ("Lack Anita ", "Kirchweg 15"),
    ("Lack Anita ", "Kirchweg 15"),
    ("Lack Anita ", "Kirchweg 15"),
    ("Lack Dominic", "Hanselmattweg 2"),
    ("Lack Dominic", "Hanselmattweg 2"),
    ("Lack Dominic", "Hanselmattweg 2"),
    ("Lack Dominic", "Hanselmattweg 2"),
    ("Lack Markus", "Schulstrasse 9"),
    ("Lack Markus", "Schulstrasse 9"),
    ("Lack Markus", "Schulstrasse 9"),
    ("Lack-Baggenstos Ignaz und Margrit", "Alte Poststrasse 10"),
    ("Lack-Baggenstos Ignaz und Margrit", "Alte Poststrasse 10"),
    ("Lack-Baggenstos Ignaz und Margrit", "Alte Poststrasse 10"),
    ("Lack-Fluri Walter + Margrit", "Allmendstrasse 14"),
    ("Lack-Fluri Walter + Margrit", "Allmendstrasse 14"),
    ("Lack-Fluri Walter + Margrit", "Allmendstrasse 14"),
    ("Lack-Wyss Paul", "Schulstrasse 14"),
    ("Lack-Wyss Paul", "Schulstrasse 14"),
    ("Lack-Wyss Paul", "Schulstrasse 14"),
    ("Lanz Kevin", "Allmend 15"),
    ("Lanz Kevin", "Allmend 15"),
    ("Lanz Kevin", "Allmend 15"),
    ("Lardon André + Nussara", "Banackerstrasse 26"),
    ("Lardon André + Nussara", "Banackerstrasse 26"),
    ("Lardon André + Nussara", "Banackerstrasse 26"),
    ("Ledermann-Keller Ernst und Manuela", "Bornstrasse 1"),
    ("Ledermann-Keller Ernst und Manuela", "Bornstrasse 1"),
    ("Ledermann-Keller Ernst und Manuela", "Bornstrasse 1"),
    ("Lenherr Andreas", "Querstrasse 1"),
    ("Lenherr Andreas", "Querstrasse 1"),
    ("Lenherr Andreas", "Querstrasse 1"),
    ("Lenherr Andreas", "Querstrasse 1"),
    ("Lenherr-Leuenberger Anita", "Eichenstrasse 1"),
    ("Lenherr-Leuenberger Anita", "Eichenstrasse 1"),
    ("Lenherr-Leuenberger Anita", "Eichenstrasse 1"),
    ("Leuenberger-Schneider Hedwig + Robert", "Schulstrasse 1"),
    ("Leuenberger-Schneider Hedwig + Robert", "Schulstrasse 1"),
    ("Leuenberger-Schneider Hedwig + Robert", "Schulstrasse 1"),
    ("Leyva Reyes + Maria Delgado Gonzalez Javier", "Niderfeld 8"),
    ("Leyva Reyes + Maria Delgado Gonzalez Javier", "Niderfeld 8"),
    ("Leyva Reyes + Maria Delgado Gonzalez Javier", "Niderfeld 8"),
    ("Liechti Kurt", "Banackerstrasse 10"),
    ("Liechti Kurt", "Banackerstrasse 10"),
    ("Liechti Kurt", "Banackerstrasse 10"),
    ("Livo AG ", "Jurastrasse 20"),
    ("Livo AG ", "Jurastrasse 20"),
    ("Livo AG ", "Jurastrasse 20"),
    ("LSB Stanzformen AG ", "Oberfeldweg 40"),
    ("LSB Stanzformen AG ", "Oberfeldweg 40"),
    ("LSB Stanzformen AG ", "Oberfeldweg 40"),
    ("LSB Stanzformen AG ", "Oberfeldweg 40"),
    ("LSB Stanzformen AG ", "Oberfeldweg 40"),
    ("LSB Stanzformen AG ", "Oberfeldweg 40"),
    ("LSB Stanzformen AG ", "Oberfeldweg 40"),
    ("Mäder-Egli Brigitte", "Allmendstrasse 22"),
    ("Mäder-Egli Brigitte", "Allmendstrasse 22"),
    ("Mäder-Egli Brigitte", "Allmendstrasse 22"),
    ("Marbet Beat", "Kirchweg 12"),
    ("Marbet Beat", "Kirchweg 12"),
    ("Marbet Beat", "Kirchweg 12"),
    ("Marbet Roland + Rosmarie", "Sonnfeldweg 23"),
    ("Marbet Roland + Rosmarie", "Sonnfeldweg 23"),
    ("Marbet Roland + Rosmarie", "Sonnfeldweg 23"),
    ("Marbet Urs", "Mittelgäustr. 73"),
    ("Marbet Urs", "Mittelgäustr. 73"),
    ("Marbet Urs", "Mittelgäustr. 73"),
    ("Marbet-Grolimund Titus und Kathrin", "Mittelgäustr. 53"),
    ("Marbet-Grolimund Titus und Kathrin", "Mittelgäustr. 53"),
    ("Marbet-Grolimund Titus und Kathrin", "Mittelgäustr. 53"),
    ("Marbet-Grolimund Titus und Kathrin", "Mittelgäustr. 53"),
    ("Marbet-Grolimund Titus und Kathrin", "Mittelgäustr. 53"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG, Gunzgen ", "Mittelgäustrasse 33"),
    ("Marbet AG ", "Markstrasse 16"),
    ("Marbet AG ", "Markstrasse 16"),
    ("Marbet AG ", "Markstrasse 16"),
    ("Marbet AG ", "Markstrasse 16"),
    ("Marbet AG ", "Markstrasse 16"),
    ("Marbet AG ", "Markstrasse 16"),
    ("Marché Restaurants Schweiz AG ", "Industriestrasse 28"),
    ("Marché Restaurants Schweiz AG ", "Industriestrasse 28"),
    ("Marché Restaurants Schweiz AG ", "Industriestrasse 28"),
    ("Maresca Sabrina Jenzer Andreas &", "Oberfeldweg 30"),
    ("Maresca Sabrina Jenzer Andreas &", "Oberfeldweg 30"),
    ("Maresca Sabrina Jenzer Andreas &", "Oberfeldweg 30"),
    ("Marinjes-Paunovic Barnislav und Mirela", "Schulstrasse 11"),
    ("Marinjes-Paunovic Barnislav und Mirela", "Schulstrasse 11"),
    ("Marinjes-Paunovic Barnislav und Mirela", "Schulstrasse 11"),
    ("Marino-Moeri Luigi und Sarah", "Mittelgäustr. 44"),
    ("Marino-Moeri Luigi und Sarah", "Mittelgäustr. 44"),
    ("Marino-Moeri Luigi und Sarah", "Mittelgäustr. 44"),
    ("Meichtry Thomas Alexandra Furrer und", "Banackerstrasse 22"),
    ("Meichtry Thomas Alexandra Furrer und", "Banackerstrasse 22"),
    ("Meichtry Thomas Alexandra Furrer und", "Banackerstrasse 22"),
    ("Meier André", "Lipsmattweg 3"),
    ("Meier André", "Lipsmattweg 3"),
    ("Meier André", "Lipsmattweg 3"),
    ("Meier-Braig Martin + Gudrun", "Eichenstrasse 14"),
    ("Meier-Braig Martin + Gudrun", "Eichenstrasse 14"),
    ("Meier-Braig Martin + Gudrun", "Eichenstrasse 14"),
    ("Meier-Holzherr Leonore", "Allmend 14"),
    ("Meier-Holzherr Leonore", "Allmend 14"),
    ("Meier-Holzherr Leonore", "Allmend 14"),
    ("Meier-Marbet Bruno und Daniela", "Markstrasse 4"),
    ("Meier-Marbet Bruno und Daniela", "Markstrasse 4"),
    ("Meier-Marbet Bruno und Daniela", "Markstrasse 4"),
    ("Meier-Schärer Monika", "Allmend 5"),
    ("Meier-Schärer Monika", "Allmend 5"),
    ("Meier-Schärer Monika", "Allmend 5"),
    ("Mertz Helmut", "Eichenstrasse 3"),
    ("Mertz Helmut", "Eichenstrasse 3"),
    ("Mertz Helmut", "Eichenstrasse 3"),
    ("Minder Marcel", "Mittelgäustr. 65"),
    ("Minder Marcel", "Mittelgäustr. 65"),
    ("Minder Marcel", "Mittelgäustr. 65"),
    ("Minder Marcel", "Mittelgäustr. 65"),
    ("Misteli Jens + Orawan", "Fulenbacherstrasse 50"),
    ("Misteli Jens + Orawan", "Fulenbacherstrasse 50"),
    ("Misteli Jens + Orawan", "Fulenbacherstrasse 50"),
    ("Misteli Jens + Orawan", "Fulenbacherstrasse 50"),
    ("Misteli Roger", "Aeschweg 33"),
    ("Misteli Roger", "Aeschweg 33"),
    ("Misteli Roger", "Aeschweg 33"),
    ("Moll Paul", "Aeschweg 20"),
    ("Moll Paul", "Aeschweg 20"),
    ("Moll Paul", "Aeschweg 20"),
    ("Moos-Wyss Hugo + Elisabeth", "Mittelgäustr. 25"),
    ("Moos-Wyss Hugo + Elisabeth", "Mittelgäustr. 25"),
    ("Moos-Wyss Hugo + Elisabeth", "Mittelgäustr. 25"),
    ("Müller Reto", "Kirchweg 9E"),
    ("Müller Reto", "Kirchweg 9E"),
    ("Müller Reto", "Kirchweg 9E"),
    ("Müller Marco Engel-Aloisi Patrizia und", "Kirchweg 11"),
    ("Müller Marco Engel-Aloisi Patrizia und", "Kirchweg 11"),
    ("Müller Marco Engel-Aloisi Patrizia und", "Kirchweg 11"),
    ("Müller Sandra + Fux Dario ", "Sonnfeldweg 24"),
    ("Müller Sandra + Fux Dario ", "Sonnfeldweg 24"),
    ("Müller Sandra + Fux Dario ", "Sonnfeldweg 24"),
    ("Natur- & Vogelschutzverein Gunzgen ", "Rüebliweg 13"),
    ("Natur- & Vogelschutzverein Gunzgen ", "Rüebliweg 13"),
    ("Natur- & Vogelschutzverein Gunzgen ", "Rüebliweg 13"),
    ("Niggli-Nimrichter Claudia", "Römerweg 9"),
    ("Niggli-Nimrichter Claudia", "Römerweg 9"),
    ("Niggli-Nimrichter Claudia", "Römerweg 9"),
    ("NSNW AG ", "Netzenstrasse 1"),
    ("NSNW AG ", "Netzenstrasse 1"),
    ("Nukic-Celikovic Sakib+Suada", "Mittelgäustrasse 11"),
    ("Nukic-Celikovic Sakib+Suada", "Mittelgäustrasse 11"),
    ("Nukic-Celikovic Sakib+Suada", "Mittelgäustrasse 11"),
    ("Nussbaum-Domig Kurt und Rosmarie", "Schulstrasse 32"),
    ("Nussbaum-Domig Kurt und Rosmarie", "Schulstrasse 32"),
    ("Nussbaum-Domig Kurt und Rosmarie", "Schulstrasse 32"),
    ("Odermatt-Kreienbühl Arnold und Beatrice", "Römerweg 31"),
    ("Odermatt-Kreienbühl Arnold und Beatrice", "Römerweg 31"),
    ("Odermatt-Kreienbühl Arnold und Beatrice", "Römerweg 31"),
    ("Orlando Michael + Andreia", "Unterfeldweg 17"),
    ("Orlando Michael + Andreia", "Unterfeldweg 17"),
    ("Orlando Michael + Andreia", "Unterfeldweg 17"),
    ("Oser Armanda", "Römerweg 15"),
    ("Oser Armanda", "Römerweg 15"),
    ("Oser Armanda", "Römerweg 15"),
    ("PARBA Parzellierungs- und Bauland AG ", "Hauptstrasse 181"),
    ("PARBA Parzellierungs- und Bauland AG ", "Hauptstrasse 181"),
    ("Patiswiss AG ", "Klärstrasse 1"),
    ("Patiswiss AG ", "Klärstrasse 1"),
    ("Patiswiss AG ", "Klärstrasse 1"),
    ("Patiswiss AG ", "Klärstrasse 1"),
    ("Peter Andreas Michael", "Alte Poststrasse 11"),
    ("Peter Andreas Michael", "Alte Poststrasse 11"),
    ("Peter Andreas Michael", "Alte Poststrasse 11"),
    ("Peter Hauser GmbH ", "Markstrasse 14"),
    ("Peter Hauser GmbH ", "Markstrasse 14"),
    ("Peter Hauser GmbH ", "Markstrasse 14"),
    ("Peter Hauser GmbH ", "Markstrasse 14"),
    ("Peter Michael + Heeb Jolanda ", "Allmend 2"),
    ("Peter Michael + Heeb Jolanda ", "Allmend 2"),
    ("Peter Michael + Heeb Jolanda ", "Allmend 2"),
    ("Pirovino-Auderset Pascale", "Schulstrasse 38"),
    ("Pirovino-Auderset Pascale", "Schulstrasse 38"),
    ("Pirovino-Auderset Pascale", "Schulstrasse 38"),
    ("Plüss-Feller Max und Margrit", "Hügelweg 5"),
    ("Plüss-Feller Max und Margrit", "Hügelweg 5"),
    ("Plüss-Feller Max und Margrit", "Hügelweg 5"),
    ("Plüss-Holliger Dominik und Marlies", "Allmend 1"),
    ("Plüss-Holliger Dominik und Marlies", "Allmend 1"),
    ("Plüss-Holliger Dominik und Marlies", "Allmend 1"),
    ("Posca-Grolimund Paolo + Nadja", "Römerweg 4"),
    ("Posca-Grolimund Paolo + Nadja", "Römerweg 4"),
    ("Posca-Grolimund Paolo + Nadja", "Römerweg 4"),
    ("Probst-Protopapa Rudolf und Erika", "Allmendstrasse 29"),
    ("Probst-Protopapa Rudolf und Erika", "Allmendstrasse 29"),
    ("Probst-Protopapa Rudolf und Erika", "Allmendstrasse 29"),
    ("Probst-Wyss Silvio und Käthi", "Alte Poststrasse 6"),
    ("Probst-Wyss Silvio und Käthi", "Alte Poststrasse 6"),
    ("Probst-Wyss Silvio und Käthi", "Alte Poststrasse 6"),
    ("Rainer Walter ", "Allmend 29"),
    ("Rainer Walter ", "Allmend 29"),
    ("Rainer Walter ", "Allmend 29"),
    ("Rainer Walter ", "Allmend 29"),
    ("Rainer Walter ", "Allmend 29"),
    ("Rausch Irene", "Unterfeldweg 19"),
    ("Rausch Irene", "Unterfeldweg 19"),
    ("Rausch Irene", "Unterfeldweg 19"),
    ("Reber Peter", "Sonnfeldweg 26"),
    ("Reber Peter", "Sonnfeldweg 26"),
    ("Reber Peter", "Sonnfeldweg 26"),
    ("Reck-Meister Yves + Alexandra", "Sonnfeldweg 8"),
    ("Reck-Meister Yves + Alexandra", "Sonnfeldweg 8"),
    ("Reck-Meister Yves + Alexandra", "Sonnfeldweg 8"),
    ("Renggli Sandro + Auer Jeanine ", "Mittelgäustrasse 15"),
    ("Renggli Sandro + Auer Jeanine ", "Mittelgäustrasse 15"),
    ("Renggli Sandro + Auer Jeanine ", "Mittelgäustrasse 15"),
    ("Resenterra-Bühlmann Tobias + Fabienne", "Jurastrasse 4"),
    ("Resenterra-Bühlmann Tobias + Fabienne", "Jurastrasse 4"),
    ("Resenterra-Bühlmann Tobias + Fabienne", "Jurastrasse 4"),
    ("Resenterra-Oberli Tony und Sonja", "Hügelweg 1"),
    ("Resenterra-Oberli Tony und Sonja", "Hügelweg 1"),
    ("Resenterra-Oberli Tony und Sonja", "Hügelweg 1"),
    ("Rhiner Rahle Grimm Daniel und", "Römerweg 19"),
    ("Rhiner Rahle Grimm Daniel und", "Römerweg 19"),
    ("Rhiner Rahle Grimm Daniel und", "Römerweg 19"),
    ("Riedel-Karsono Andreas+Tita", "Mittelgäustr. 17"),
    ("Riedel-Karsono Andreas+Tita", "Mittelgäustr. 17"),
    ("Riedel-Karsono Andreas+Tita", "Mittelgäustr. 17"),
    ("Rieser Stefan und Sarah", "Banackerstrasse 22A"),
    ("Rieser Stefan und Sarah", "Banackerstrasse 22A"),
    ("Rieser Stefan und Sarah", "Banackerstrasse 22A"),
    ("Röm.-Kath. Kirchgemeinde Gunzgen ", "Kaltbachstrasse 5"),
    ("Röm.-Kath. Kirchgemeinde Gunzgen ", "Kaltbachstrasse 5"),
    ("Röm.-Kath. Kirchgemeinde Gunzgen ", "Kaltbachstrasse 5"),
    ("Röm.-Kath. Kirchgemeinde Gunzgen ", "Kaltbachstrasse 5"),
    ("Röm.-Kath. Kirchgemeinde Gunzgen ", "Kaltbachstrasse 5"),
    ("Röm.-Kath. Kirchgemeinde Gunzgen ", "Kaltbachstrasse 5"),
    ("Rötheli-von Arb Urs und Cornelia", "Unterfeldweg 14"),
    ("Rötheli-von Arb Urs und Cornelia", "Unterfeldweg 14"),
    ("Rötheli-von Arb Urs und Cornelia", "Unterfeldweg 14"),
    ("Röthlisberger Walter", "Aeschweg 8"),
    ("Röthlisberger Walter", "Aeschweg 8"),
    ("Röthlisberger Walter", "Aeschweg 8"),
    ("Rohde-Baumgartner Maria", "Thalackerweg 11"),
    ("Rohde-Baumgartner Maria", "Thalackerweg 11"),
    ("Rohde-Baumgartner Maria", "Thalackerweg 11"),
    ("Rohde-Salerno Jürgen und Angelika", "Oberfeldweg 13"),
    ("Rohde-Salerno Jürgen und Angelika", "Oberfeldweg 13"),
    ("Rohde-Salerno Jürgen und Angelika", "Oberfeldweg 13"),
    ("Romano Adriano", "Wangenweg 16"),
    ("Romano Adriano", "Wangenweg 16"),
    ("Romano Adriano", "Wangenweg 16"),
    ("Romano Pargätzi Herr", "Höllweg 2"),
    ("Romano Pargätzi Herr", "Höllweg 2"),
    ("Romano Pargätzi Herr", "Höllweg 2"),
    ("Roth-Dach GmbH ", "Mittelgäustr. 77"),
    ("Roth-Dach GmbH ", "Mittelgäustr. 77"),
    ("Roth-Dach GmbH ", "Mittelgäustr. 77"),
    ("Rothenbühler Remo + Sévérine Danielle", "Jurastrasse 1"),
    ("Rothenbühler Remo + Sévérine Danielle", "Jurastrasse 1"),
    ("Rothenbühler Remo + Sévérine Danielle", "Jurastrasse 1"),
    ("Royal Handels AG ", "Tiergartenweg 1"),
    ("Royal Handels AG ", "Tiergartenweg 1"),
    ("Royal Handels AG ", "Tiergartenweg 1"),
    ("Ruckstuhl Elisabeth Bauert Bruno und", "Eichenstrasse 2"),
    ("Ruckstuhl Elisabeth Bauert Bruno und", "Eichenstrasse 2"),
    ("Ruckstuhl Elisabeth Bauert Bruno und", "Eichenstrasse 2"),
    ("Rüegger-Baier Mario und Evelyne", "Aeschweg 11"),
    ("Rüegger-Baier Mario und Evelyne", "Aeschweg 11"),
    ("Rüegger-Baier Mario und Evelyne", "Aeschweg 11"),
    ("Rufibach-Born Peter", "Banackerstrasse 20"),
    ("Rufibach-Born Peter", "Banackerstrasse 20"),
    ("Rufibach-Born Peter", "Banackerstrasse 20"),
    ("Ruppen-Dörfliger Martin + Jasmin", "Hanselmattweg 3"),
    ("Ruppen-Dörfliger Martin + Jasmin", "Hanselmattweg 3"),
    ("Ruppen-Dörfliger Martin + Jasmin", "Hanselmattweg 3"),
    ("Ryf-Stiner Hanspeter und Barbara", "Mittelgäustr. 33"),
    ("Ryf-Stiner Hanspeter und Barbara", "Mittelgäustr. 33"),
    ("Ryf-Stiner Hanspeter und Barbara", "Mittelgäustr. 33"),
    ("Saner-Kamber Oliver + Regula", "Industriestrasse 1"),
    ("Saner-Kamber Oliver + Regula", "Industriestrasse 1"),
    ("Saner-Kamber Oliver + Regula", "Industriestrasse 1"),
    ("Saner-Steiner Daniel + Daniela", "Bornstrasse 7"),
    ("Saner-Steiner Daniel + Daniela", "Bornstrasse 7"),
    ("Saner-Steiner Daniel + Daniela", "Bornstrasse 7"),
    ("Sascha Beck + Stefanie Geiser ", "Oberfeldweg 34"),
    ("Sascha Beck + Stefanie Geiser ", "Oberfeldweg 34"),
    ("Sascha Beck + Stefanie Geiser ", "Oberfeldweg 34"),
    ("Schär-Kölliker René + Marlies", "Römerweg 8"),
    ("Schär-Kölliker René + Marlies", "Römerweg 8"),
    ("Schär-Kölliker René + Marlies", "Römerweg 8"),
    ("Schärer Christian", "Sonnfeldweg 2"),
    ("Schärer Christian", "Sonnfeldweg 2"),
    ("Schärer Christian", "Sonnfeldweg 2"),
    ("Schafer-Forrer Gregor + Vreni", "Mittelgäustr. 23"),
    ("Schafer-Forrer Gregor + Vreni", "Mittelgäustr. 23"),
    ("Schafer-Forrer Gregor + Vreni", "Mittelgäustr. 23"),
    ("Schenker-Merz Erhard und Susi", "Hügelweg 9"),
    ("Schenker-Merz Erhard und Susi", "Hügelweg 9"),
    ("Schenker-Merz Erhard und Susi", "Hügelweg 9"),
    ("Schickling-Gasser Bernhard + Monika", "Allmend 3"),
    ("Schickling-Gasser Bernhard + Monika", "Allmend 3"),
    ("Schickling-Gasser Bernhard + Monika", "Allmend 3"),
    ("Schläfli Urs + Isabelle", "Grabenweg 6"),
    ("Schläfli Urs + Isabelle", "Grabenweg 6"),
    ("Schläfli Urs + Isabelle", "Grabenweg 6"),
    ("Schläfli Corina Studer Manfred und", "Grabenweg 4"),
    ("Schläfli Corina Studer Manfred und", "Grabenweg 4"),
    ("Schläfli Corina Studer Manfred und", "Grabenweg 4"),
    ("Schlegel-Günthart Hansruedi und Iris", "Aeschweg 49"),
    ("Schlegel-Günthart Hansruedi und Iris", "Aeschweg 49"),
    ("Schlegel-Günthart Hansruedi und Iris", "Aeschweg 49"),
    ("Schlossimmobilien AG ", ""),
    ("Schlossimmobilien AG ", ""),
    ("Schlossimmobilien AG ", ""),
    ("Schmid Urs", "Jurastrasse 3"),
    ("Schmid Urs", "Jurastrasse 3"),
    ("Schmid Urs", "Jurastrasse 3"),
    ("Schmid-Bannwart Thomas und Astrid", "Querstrasse 3"),
    ("Schmid-Bannwart Thomas und Astrid", "Querstrasse 3"),
    ("Schmid-Bannwart Thomas und Astrid", "Querstrasse 3"),
    ("Schmid-Rauber Adalbert und Marianne", "Mittelgäustr. 59"),
    ("Schmid-Rauber Adalbert und Marianne", "Mittelgäustr. 59"),
    ("Schmid-Rauber Adalbert und Marianne", "Mittelgäustr. 59"),
    ("Schmied Lukas", "Kirchweg 8"),
    ("Schmied Lukas", "Kirchweg 8"),
    ("Schmied Lukas", "Kirchweg 8"),
    ("Schnyder Alfred", "Allmendstrasse 21"),
    ("Schnyder Alfred", "Allmendstrasse 21"),
    ("Schönenberger Urs", "Allmend 23"),
    ("Schönenberger Urs", "Allmend 23"),
    ("Schönenberger Urs", "Allmend 23"),
    ("Schöpfer-Köppel Fritz", "Aeschweg 23"),
    ("Schöpfer-Köppel Fritz", "Aeschweg 23"),
    ("Schöpfer-Köppel Fritz", "Aeschweg 23"),
    ("Schrag Sanja Lüthi Martin und", "Kreuzstrasse 7"),
    ("Schrag Sanja Lüthi Martin und", "Kreuzstrasse 7"),
    ("Schrag Sanja Lüthi Martin und", "Kreuzstrasse 7"),
    ("Schreinerei Nimrichter Daniel ", "Römerweg 9"),
    ("Schreinerei Nimrichter Daniel ", "Römerweg 9"),
    ("Schreinerei Nimrichter Daniel ", "Römerweg 9"),
    ("Schüpbach Erich", "Banackerstrasse 4"),
    ("Schüpbach Erich", "Banackerstrasse 4"),
    ("Schüpbach Erich", "Banackerstrasse 4"),
    ("Schürch-Uebelhard Ruth", "Unterfeldweg 9"),
    ("Schürch-Uebelhard Ruth", "Unterfeldweg 9"),
    ("Schürch-Uebelhard Ruth", "Unterfeldweg 9"),
    ("Schützengesellschaft Gunzgen-Boningen ", "Niederhofweg 2"),
    ("Schweiz. Vereinigung für ", "Rigistrasse 2"),
    ("Schweiz. Vereinigung für ", "Rigistrasse 2"),
    ("Schweiz. Vereinigung für ", "Rigistrasse 2"),
    ("Schweizer Silvia", "Aeschweg 55"),
    ("Schweizer Silvia", "Aeschweg 55"),
    ("Schweizer Silvia", "Aeschweg 55"),
    ("Scuderi-Kölliker Renate", "Aeschweg 45"),
    ("Scuderi-Kölliker Renate", "Aeschweg 45"),
    ("Scuderi-Kölliker Renate", "Aeschweg 45"),
    ("Sellakandu Vinyahalingam", "Banackerstrasse"),
    ("Sellakandu Vinyahalingam", "Banackerstrasse"),
    ("Sellakandu Vinyahalingam", "Banackerstrasse"),
    ("Sembinelli Fabienne", "Banackerstrasse 28 A"),
    ("Sembinelli Fabienne", "Banackerstrasse 28 A"),
    ("Sembinelli Fabienne", "Banackerstrasse 28 A"),
    ("Sengür-Anac Kemal + Nursel", "Banackerstrasse 24"),
    ("Sengür-Anac Kemal + Nursel", "Banackerstrasse 24"),
    ("Sengür-Anac Kemal + Nursel", "Banackerstrasse 24"),
    ("Serifovic-Taletovic Sahbudin und Bersija", "Neuhüslermatt 10"),
    ("Serifovic-Taletovic Sahbudin und Bersija", "Neuhüslermatt 10"),
    ("Serifovic-Taletovic Sahbudin und Bersija", "Neuhüslermatt 10"),
    ("Serifovic-Taletovic Sahbudin und Bersija", "Neuhüslermatt 10"),
    ("Serifovic-Taletovic Sahbudin und Bersija", "Neuhüslermatt 10"),
    ("Serifovic-Taletovic Sahbudin und Bersija", "Neuhüslermatt 10"),
    ("Smajic Eldin und Mirela", "Sonnfeldweg 15"),
    ("Smajic Eldin und Mirela", "Sonnfeldweg 15"),
    ("Smajic Eldin und Mirela", "Sonnfeldweg 15"),
    ("SMR Stanztechnik AG ", "Markstrasse 10"),
    ("SMR Stanztechnik AG ", "Markstrasse 10"),
    ("SMR Stanztechnik AG ", "Markstrasse 10"),
    ("Sollberger Willy", "Merkurstrasse 25"),
    ("Sollberger Willy", "Merkurstrasse 25"),
    ("Sollberger Willy", "Merkurstrasse 25"),
    ("Sollberger-Gabi Daniel + Nadia", "Sonnfeldweg 22"),
    ("Sollberger-Gabi Daniel + Nadia", "Sonnfeldweg 22"),
    ("Sollberger-Gabi Daniel + Nadia", "Sonnfeldweg 22"),
    ("Sommer-Schweizer Rainer und Barbara", "Römerweg 25"),
    ("Sommer-Schweizer Rainer und Barbara", "Römerweg 25"),
    ("Sommer-Schweizer Rainer und Barbara", "Römerweg 25"),
    ("Sommer Anuschka Aeschimann Matthias und", "Allmendstrasse 30"),
    ("Sommer Anuschka Aeschimann Matthias und", "Allmendstrasse 30"),
    ("Sommer Anuschka Aeschimann Matthias und", "Allmendstrasse 30"),
    ("Sommerhalder Nicole", "Kirchweg 1"),
    ("Sommerhalder Nicole", "Kirchweg 1"),
    ("Sommerhalder Nicole", "Kirchweg 1"),
    ("Spasic Mihajlo und Tanja", "Allmendstrasse 3"),
    ("Spasic Mihajlo und Tanja", "Allmendstrasse 3"),
    ("Spasic Mihajlo und Tanja", "Allmendstrasse 3"),
    ("Spielmann-Husi Stefan und Lilo", "Aeschweg 9"),
    ("Spielmann-Husi Stefan und Lilo", "Aeschweg 9"),
    ("Spielmann-Husi Stefan und Lilo", "Aeschweg 9"),
    ("Srisathiyaanantham Mayuren", "Banackerstrasse 26A"),
    ("Srisathiyaanantham Mayuren", "Banackerstrasse 26A"),
    ("Srisathiyaanantham Mayuren", "Banackerstrasse 26A"),
    ("Stecher Mario und Julia", "Bornstrasse 8"),
    ("Stecher Mario und Julia", "Bornstrasse 8"),
    ("Stecher Mario und Julia", "Bornstrasse 8"),
    ("Steiner-Guggisberg Hansjörg und Heidi", "Aeschweg 2"),
    ("Steiner-Guggisberg Hansjörg und Heidi", "Aeschweg 2"),
    ("Steiner-Guggisberg Hansjörg und Heidi", "Aeschweg 2"),
    ("Steinmann-Berger Nicole", "Sonnfeldweg 18"),
    ("Steinmann-Berger Nicole", "Sonnfeldweg 18"),
    ("Steinmann-Berger Nicole", "Sonnfeldweg 18"),
    ("Stelzer Frank + Cornelia", "Allmendstrasse 9"),
    ("Stelzer Frank + Cornelia", "Allmendstrasse 9"),
    ("Stelzer Frank + Cornelia", "Allmendstrasse 9"),
    ("Sterboca Lucie Affolter David und", "Allmend 7"),
    ("Sterboca Lucie Affolter David und", "Allmend 7"),
    ("Sterboca Lucie Affolter David und", "Allmend 7"),
    ("Stowe Banackerstr.36, Gunzgen ", "Waldeggstrasse 10"),
    ("Stowe Banackerstr.36, Gunzgen ", "Waldeggstrasse 10"),
    ("Stowe Banackerstr.36, Gunzgen ", "Waldeggstrasse 10"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Eigentümergemeinschaft ", "Dorfstrasse 13, Postfach 60"),
    ("STOWE Zentrum Gunzgen ", "Zielempgasse 16"),
    ("STOWE Zentrum Gunzgen ", "Zielempgasse 16"),
    ("STOWE Zentrum Gunzgen ", "Zielempgasse 16"),
    ("STOWE Zentrum Gunzgen ", "Zielempgasse 16"),
    ("Strub-Calderoni Julius und Attilia", "Aeschweg 16"),
    ("Strub-Calderoni Julius und Attilia", "Aeschweg 16"),
    ("Strub-Calderoni Julius und Attilia", "Aeschweg 16"),
    ("Studer Anton", "Solothurnerstrasse 27"),
    ("Studer Anton", "Solothurnerstrasse 27"),
    ("Studer Anton", "Solothurnerstrasse 27"),
    ("Studer Anton", "Solothurnerstrasse 27"),
    ("Studer Brigitte", "Banackerstrasse 24A"),
    ("Studer Brigitte", "Banackerstrasse 24A"),
    ("Studer Brigitte", "Banackerstrasse 24A"),
    ("Studer  Bruno", "Fulenbachstrasse 48"),
    ("Studer  Bruno", "Fulenbachstrasse 48"),
    ("Studer  Bruno", "Fulenbachstrasse 48"),
    ("Studer  Eveline", "Markstrasse 1"),
    ("Studer  Eveline", "Markstrasse 1"),
    ("Studer  Eveline", "Markstrasse 1"),
    ("Studer René", "Römerweg Ost 1"),
    ("Studer René", "Römerweg Ost 1"),
    ("Studer René", "Römerweg Ost 1"),
    ("Studer Stefan", "Markstrasse 6"),
    ("Studer Stefan", "Markstrasse 6"),
    ("Studer Stefan", "Markstrasse 6"),
    ("Studer Thomas", "Oberfeldweg 16"),
    ("Studer Thomas", "Oberfeldweg 16"),
    ("Studer Thomas", "Oberfeldweg 16"),
    ("Studer-Berger Thomas und Pia", "Aeschweg 4"),
    ("Studer-Berger Thomas und Pia", "Aeschweg 4"),
    ("Studer-Berger Thomas und Pia", "Aeschweg 4"),
    ("Studer-Reinhard Hansruedi und Monika", "Markstrasse 2"),
    ("Studer-Reinhard Hansruedi und Monika", "Markstrasse 2"),
    ("Studer-Reinhard Hansruedi und Monika", "Markstrasse 2"),
    ("Studer-Sansonnens Urs + Anny", "Rosenweg 2"),
    ("Studer-Sansonnens Urs + Anny", "Rosenweg 2"),
    ("Studer-Sansonnens Urs + Anny", "Rosenweg 2"),
    ("Studer-Woodtli Thomas und Samantha", "Oberfeldweg 16"),
    ("Studer-Woodtli Thomas und Samantha", "Oberfeldweg 16"),
    ("Studer-Woodtli Thomas und Samantha", "Oberfeldweg 16"),
    ("Studer-Wyss Günter", "Aeschweg 26"),
    ("Studer-Wyss Günter", "Aeschweg 26"),
    ("Studer-Wyss Günter", "Aeschweg 26"),
    ("Studer-Wyss Günter und Regula", "Aeschweg 26"),
    ("Studer-Wyss Günter und Regula", "Aeschweg 26"),
    ("Studer-Wyss Günter und Regula", "Aeschweg 26"),
    ("Studer-Zeltner Peter", "Lischmatt 1"),
    ("Studer-Zeltner Peter", "Lischmatt 1"),
    ("Studer-Zeltner Peter", "Lischmatt 1"),
    ("Studer-Zürcher Reinhold und Edith", "Allmendstrasse 23"),
    ("Studer-Zürcher Reinhold und Edith", "Allmendstrasse 23"),
    ("Studer-Zürcher Reinhold und Edith", "Allmendstrasse 23"),
    ("Stutz Fabienne Hunziker Marc und", "Römerweg 6"),
    ("Stutz Fabienne Hunziker Marc und", "Römerweg 6"),
    ("Stutz Fabienne Hunziker Marc und", "Römerweg 6"),
    ("STWE Eigentümergemeinschaft MFH Kirchweg 17, Gunzgen ", "Kirchweg 17"),
    ("STWE Eigentümergemeinschaft MFH Kirchweg 17, Gunzgen ", "Kirchweg 17"),
    ("STWE Eigentümergemeinschaft MFH Kirchweg 17, Gunzgen ", "Kirchweg 17"),
    ("STWEG Banackerstrasse 34, Gunzgen ", "Waldeggstrasse 10"),
    ("STWEG Banackerstrasse 34, Gunzgen ", "Waldeggstrasse 10"),
    ("STWEG Banackerstrasse 34, Gunzgen ", "Waldeggstrasse 10"),
    ("STWEG Lipsmattweg Gunzgen ", "Solothurnerstrasse 233"),
    ("STWEG Lipsmattweg Gunzgen ", "Solothurnerstrasse 233"),
    ("STWEG Lipsmattweg Gunzgen ", "Solothurnerstrasse 233"),
    ("STWEG Mittelgäustrasse 37+39 ", "Mittelgäustrasse 37"),
    ("STWEG Mittelgäustrasse 37+39 ", "Mittelgäustrasse 37"),
    ("STWEG Mittelgäustrasse 37+39 ", "Mittelgäustrasse 37"),
    ("STWEG Mittelgäustrasse 37+39 ", "Mittelgäustrasse 37"),
    ("STWEG Niderfeld 1 Gunzgen ", "Kürzestrasse 31"),
    ("STWEG Niderfeld 1 Gunzgen ", "Kürzestrasse 31"),
    ("STWEG Niderfeld 1 Gunzgen ", "Kürzestrasse 31"),
    ("Stweg Römerweg Ost 4 ", "Grossmatt 18"),
    ("Stweg Römerweg Ost 4 ", "Grossmatt 18"),
    ("Stweg Römerweg Ost 4 ", "Grossmatt 18"),
    ("Suba Gastro GmbH ", "Allmend 31"),
    ("Suba Gastro GmbH ", "Allmend 31"),
    ("Suba Gastro GmbH ", "Allmend 31"),
    ("Suba Gastro GmbH ", "Allmend 31"),
    ("Syla Behxhet + Haziraj-Syla Shepresa ", "Allmendstrasse 17"),
    ("Syla Behxhet + Haziraj-Syla Shepresa ", "Allmendstrasse 17"),
    ("Teddybär - Bärenstarke Kinderbetreuung AG ", "Meisenweg 1"),
    ("Teddybär - Bärenstarke Kinderbetreuung AG ", "Meisenweg 1"),
    ("Teddybär - Bärenstarke Kinderbetreuung AG ", "Meisenweg 1"),
    ("Thi Yen Loan Chhing Peng und", "Römerweg 1"),
    ("Thi Yen Loan Chhing Peng und", "Römerweg 1"),
    ("Thi Yen Loan Chhing Peng und", "Römerweg 1"),
    ("Thommen Rolf", "Aeschweg 21"),
    ("Thommen Rolf", "Aeschweg 21"),
    ("Thommen Rolf", "Aeschweg 21"),
    ("Thorsell-Aerni Olle + Saskia", "Aeschweg 6"),
    ("Thorsell-Aerni Olle + Saskia", "Aeschweg 6"),
    ("Thorsell-Aerni Olle + Saskia", "Aeschweg 6"),
    ("Tiemann-Misteli Remo+Andrea", "Kirchweg 9a"),
    ("Tiemann-Misteli Remo+Andrea", "Kirchweg 9a"),
    ("Tiemann-Misteli Remo+Andrea", "Kirchweg 9a"),
    ("Toplanaj Edmond", "Banackerstrasse 19"),
    ("Toplanaj Edmond", "Banackerstrasse 19"),
    ("Toplanaj Edmond", "Banackerstrasse 19"),
    ("Trachsel Claudia", "Sonnfeldweg 16"),
    ("Trachsel Claudia", "Sonnfeldweg 16"),
    ("Trachsel Claudia", "Sonnfeldweg 16"),
    ("Trachsler Thomas + Michelle", "Allmendstrasse 35"),
    ("Trachsler Thomas + Michelle", "Allmendstrasse 35"),
    ("Trachsler Thomas + Michelle", "Allmendstrasse 35"),
    ("Translait SA ", "Industriestrasse 16"),
    ("Translait SA ", "Industriestrasse 16"),
    ("Translait SA ", "Industriestrasse 16"),
    ("Translait SA ", "Industriestrasse 16"),
    ("Trösch Corinne Fürst Carmen und", "Bornstrasse 16"),
    ("Trösch Corinne Fürst Carmen und", "Bornstrasse 16"),
    ("Trösch Corinne Fürst Carmen und", "Bornstrasse 16"),
    ("Troxler-Grob Daniel + Susi", "Lischmatt 5"),
    ("Troxler-Grob Daniel + Susi", "Lischmatt 5"),
    ("Troxler-Grob Daniel + Susi", "Lischmatt 5"),
    ("Uhlmann Rudolf", "Allmend 19"),
    ("Uhlmann Rudolf", "Allmend 19"),
    ("Uhlmann Rudolf", "Allmend 19"),
    ("Urso Raffaele + Mary", "Banackerstrasse 18"),
    ("Urso Raffaele + Mary", "Banackerstrasse 18"),
    ("Urso Raffaele + Mary", "Banackerstrasse 18"),
    ("Valora Schweiz SA ", "Hofackerstrasse 40"),
    ("Valora Schweiz SA ", "Hofackerstrasse 40"),
    ("Valora Schweiz SA ", "Hofackerstrasse 40"),
    ("Valora Schweiz SA ", "Hofackerstrasse 40"),
    ("Valora Schweiz SA ", "Hofackerstrasse 40"),
    ("Valora Schweiz SA ", "Hofackerstrasse 40"),
    ("Vanotti-Degen Marco und Daniela", "Markstrasse 15"),
    ("Vanotti-Degen Marco und Daniela", "Markstrasse 15"),
    ("Vanotti-Degen Marco und Daniela", "Markstrasse 15"),
    ("Verwaltung STWE Römerweg Ost 8 ", "Römerweg Ost 8"),
    ("Verwaltung STWE Römerweg Ost 8 ", "Römerweg Ost 8"),
    ("Verwaltung STWE Römerweg Ost 8 ", "Römerweg Ost 8"),
    ("Verwaltung STWE Römerweg Ost 8 ", "Römerweg Ost 8"),
    ("Verwaltung STWE Römerweg Ost 8 ", "Römerweg Ost 8"),
    ("Verwaltung STWE Römerweg Ost 8 ", "Römerweg Ost 8"),
    ("Villars-Ganz Marcel und Madeleine", "Aeschweg 31"),
    ("Villars-Ganz Marcel und Madeleine", "Aeschweg 31"),
    ("Villars-Ganz Marcel und Madeleine", "Aeschweg 31"),
    ("Vogel-Giger Albert", "Unterfeldweg 5"),
    ("Vogel-Giger Albert", "Unterfeldweg 5"),
    ("Vogel-Giger Albert", "Unterfeldweg 5"),
    ("Vogel-Lang Johann + Beatrice", "Kaiserstuhlerstrasse 77"),
    ("Vogel-Lang Johann + Beatrice", "Kaiserstuhlerstrasse 77"),
    ("von Arb-Aerni Agnes", "Aeschweg 12"),
    ("von Arb-Aerni Agnes", "Aeschweg 12"),
    ("von Arb-Aerni Agnes", "Aeschweg 12"),
    ("Von Arx Adrian und Monika", "Römerweg 14"),
    ("Von Arx Adrian und Monika", "Römerweg 14"),
    ("Von Arx Adrian und Monika", "Römerweg 14"),
    ("von Arx Karin", "Sonnfeldweg 12"),
    ("von Arx Karin", "Sonnfeldweg 12"),
    ("von Arx Karin", "Sonnfeldweg 12"),
    ("von Arx Reto", "Markstrasse 9"),
    ("von Arx Reto", "Markstrasse 9"),
    ("von Arx Reto", "Markstrasse 9"),
    ("von Arx-Müller Marco und Manuela", "Alte Poststrasse 15"),
    ("von Arx-Müller Marco und Manuela", "Alte Poststrasse 15"),
    ("von Arx-Müller Marco und Manuela", "Alte Poststrasse 15"),
    ("von Arx-Wyss Jörg und Helen", "Markstrasse 21"),
    ("von Arx-Wyss Jörg und Helen", "Markstrasse 21"),
    ("von Arx-Wyss Jörg und Helen", "Markstrasse 21"),
    ("von Atzigen-Gloor Alois und Barbara", "Rosenweg 4"),
    ("von Atzigen-Gloor Alois und Barbara", "Rosenweg 4"),
    ("von Atzigen-Gloor Alois und Barbara", "Rosenweg 4"),
    ("von Büren Gabriel + Monika", "Schulstrasse 26"),
    ("von Büren Gabriel + Monika", "Schulstrasse 26"),
    ("von Büren Gabriel + Monika", "Schulstrasse 26"),
    ("von Felten Daniel + Sabine", "Lilienweg 4"),
    ("von Felten Daniel + Sabine", "Lilienweg 4"),
    ("von Felten Daniel + Sabine", "Lilienweg 4"),
    ("Wagner Peter", "Römerweg 21"),
    ("Wagner Peter", "Römerweg 21"),
    ("Wagner Peter", "Römerweg 21"),
    ("Wagner-Gyger Lotti", "Schulstrasse 34"),
    ("Wagner-Gyger Lotti", "Schulstrasse 34"),
    ("Wagner-Gyger Lotti", "Schulstrasse 34"),
    ("Wagner-Stulz Thomas + Sandra", "Allmend 16"),
    ("Wagner-Stulz Thomas + Sandra", "Allmend 16"),
    ("Wagner-Stulz Thomas + Sandra", "Allmend 16"),
    ("Waldmann Hedi", "Höllweg 3"),
    ("Waldmann Hedi", "Höllweg 3"),
    ("Waldmann Hedi", "Höllweg 3"),
    ("Walker-Grepper Jean-Claude und Senta", "Jurastrasse 2"),
    ("Walker-Grepper Jean-Claude und Senta", "Jurastrasse 2"),
    ("Walker-Grepper Jean-Claude und Senta", "Jurastrasse 2"),
    ("Walter-Keusch Heinz + Andrea", "Römerweg 17"),
    ("Walter-Keusch Heinz + Andrea", "Römerweg 17"),
    ("Walter-Keusch Heinz + Andrea", "Römerweg 17"),
    ("Wasmer-Eschmann Ronny+Nadia", "Schulstrasse 16"),
    ("Wasmer-Eschmann Ronny+Nadia", "Schulstrasse 16"),
    ("Wasmer-Eschmann Ronny+Nadia", "Schulstrasse 16"),
    ("Weber-Notter Gerold und Manuela", "Oberfeldweg 19"),
    ("Weber-Notter Gerold und Manuela", "Oberfeldweg 19"),
    ("Weber-Notter Gerold und Manuela", "Oberfeldweg 19"),
    ("Wechsler Marietta Lenzin Rolf &", "Moos"),
    ("Wechsler Marietta Lenzin Rolf &", "Moos"),
    ("Wechsler Marietta Lenzin Rolf &", "Moos"),
    ("Wegmüller-Achermann Elsbeth", "Sonnfeldweg 34"),
    ("Wegmüller-Achermann Elsbeth", "Sonnfeldweg 34"),
    ("Wegmüller-Achermann Elsbeth", "Sonnfeldweg 34"),
    ("Weh-Studer Michael + Sandra", "Sonnfeldweg 10"),
    ("Weh-Studer Michael + Sandra", "Sonnfeldweg 10"),
    ("Weh-Studer Michael + Sandra", "Sonnfeldweg 10"),
    ("Weibel-Piunti Martin und Giuliana", "Weidweg 10"),
    ("Weibel-Piunti Martin und Giuliana", "Weidweg 10"),
    ("Weibel-Piunti Martin und Giuliana", "Weidweg 10"),
    ("Widmer Vreni", "Schulstrasse 30"),
    ("Widmer Vreni", "Schulstrasse 30"),
    ("Widmer Vreni", "Schulstrasse 30"),
    ("Widmer-Fluri Silvia", "Markstrasse 19"),
    ("Widmer-Fluri Silvia", "Markstrasse 19"),
    ("Widmer-Fluri Silvia", "Markstrasse 19"),
    ("Widmer-Lanz Peter + Ursula", "Allmend 27"),
    ("Widmer-Lanz Peter + Ursula", "Allmend 27"),
    ("Widmer-Lanz Peter + Ursula", "Allmend 27"),
    ("Wissner Dirk + Myriam", "Niederfeld 6"),
    ("Wissner Dirk + Myriam", "Niederfeld 6"),
    ("Wissner Dirk + Myriam", "Niederfeld 6"),
    ("Wohlgemuth Rolf + Monika", "Sonnfeldweg 32"),
    ("Wohlgemuth Rolf + Monika", "Sonnfeldweg 32"),
    ("Wohlgemuth Rolf + Monika", "Sonnfeldweg 32"),
    ("Wohnplus AG ", "Birmensdorferstrasse 140"),
    ("Wohnplus AG ", "Birmensdorferstrasse 140"),
    ("Wohnplus AG ", "Birmensdorferstrasse 140"),
    ("WyB Immobilien Wyss ", "Grossmatt"),
    ("WyB Immobilien Wyss ", "Grossmatt"),
    ("WyB Immobilien Wyss ", "Grossmatt"),
    ("Wyss-Hug Hans + Maria", "Mittelgäustr. 49"),
    ("Wyss-Hug Hans + Maria", "Mittelgäustr. 49"),
    ("Wyss-Hug Hans + Maria", "Mittelgäustr. 49"),
    ("Wyss-Hug Hans + Maria", "Mittelgäustr. 49"),
    ("Wyss-Hunkeler Erich und Rosmarie", "Schulstrasse 10"),
    ("Wyss-Hunkeler Erich und Rosmarie", "Schulstrasse 10"),
    ("Wyss-Hunkeler Erich und Rosmarie", "Schulstrasse 10"),
    ("Wyss-Meier Thomas + Margreth", "Oberfeldweg 17"),
    ("Wyss-Meier Thomas + Margreth", "Oberfeldweg 17"),
    ("Wyss-Meier Thomas + Margreth", "Oberfeldweg 17"),
    ("Wyss-Schibli Lukas und Susanne", "Aeschweg 39"),
    ("Wyss-Schibli Lukas und Susanne", "Aeschweg 39"),
    ("Wyss-Schibli Lukas und Susanne", "Aeschweg 39"),
    ("Wyss-Tüscher Beat und Barbara", "Niderfeld 14"),
    ("Wyss-Tüscher Beat und Barbara", "Niderfeld 14"),
    ("Wyss-Tüscher Beat und Barbara", "Niderfeld 14"),
    ("Zahno Josef + Barbara Berchtold ", "Ghölstrasse 12"),
    ("Zahno Josef + Barbara Berchtold ", "Ghölstrasse 12"),
    ("Zahno Josef + Barbara Berchtold ", "Ghölstrasse 12"),
    ("Ziegler Michael", "Grabenweg 2"),
    ("Ziegler Michael", "Grabenweg 2"),
    ("Ziegler Michael", "Grabenweg 2"),
    ("Zieri Stefan + Fürst Fabienne ", "Unterfeldweg 10"),
    ("Zieri Stefan + Fürst Fabienne ", "Unterfeldweg 10"),
    ("Zieri Stefan + Fürst Fabienne ", "Unterfeldweg 10"),
    ("Zurbuchen Erwin", "Mittelgäustr. 56"),
    ("Zurbuchen Erwin", "Mittelgäustr. 56"),
    ("Zurbuchen Erwin", "Mittelgäustr. 56"),
    ("Zweckverband  ", "Klärstrasse 12"),
    ("Zweckverband  ", "Klärstrasse 12"),
    ("Zweckverband ", "Klärstrasse 12"),
    ("Zweckverband ", "Klärstrasse 12"),
    ("Zweckverband ", "Klärstrasse 12"),
    ("Zweckverband ", "Klärstrasse 12"),
    ("Zweckverband ", "Klärstrasse 12"),
    ("Zweckverband ", "Klärstrasse 12"),
    ("Zweckverband ", "Klärstrasse 12")
]

for name, street in addresses:
    
    streets = set([n for n, s in addresses if n == name])
    if len(streets) > 1:
        print(addr)
    if len(streets) < 1:
        print(addr)